import { useCallback, useEffect, useMemo, useState } from 'react'
import { Accordion, AccordionDetails, AccordionSummary, Alert, Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Divider, MenuItem, Paper, Stack, Tab, Tabs, TextField, Typography } from '@mui/material'
import ExpandMoreOutlinedIcon from '@mui/icons-material/ExpandMoreOutlined'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../hooks/useAuth'

type WindowKey='24h'|'7d'|'30d'
type Company={id:string;name:string;slug:string;active:boolean;members:number;projects:number;sites:number;employees:number;unready:number;line_groups:number;open_errors:number;children:Array<{id:string;name:string;code?:string;status:string;sites:Array<{id:string;name:string;active:boolean;employees:number}>}>}
type Row=Record<string,string|number|boolean|null|undefined>
type Snapshot={generated_at:string;window:WindowKey;window_started_at:string;kpis:Record<string,number>;trend:Array<{bucket:string;healthy:number;warning:number;critical:number;runs:number}>;companies:Company[];work_items:Row[];errors:Row[];health:Row[];top_slow:Row[];audit:Row[];error_summary:Record<string,number>;communication:Record<string,number>;workforce:Record<string,number>;metric_definitions:Array<{key:string;label:string;definition:string}>}
type Detail={title:string;rows:Array<{label:string;value:string;note?:string}>}|null
const colors={healthy:'#2E7D52',warning:'#C27414',critical:'#C63D3D',unknown:'#757575'}
const fmt=(value:number|undefined)=>new Intl.NumberFormat('th-TH').format(value??0)
const windows:Record<WindowKey,string>={"24h":'24 ชั่วโมง',"7d":'7 วัน',"30d":'30 วัน'}
const pairs=(source:Record<string,number>,labels:Record<string,string>)=>Object.entries(labels).map(([key,label])=>({label,value:fmt(source[key])}))

export function PlatformControlCenterPage(){
  const {profile,switchCompany}=useAuth()
  const [data,setData]=useState<Snapshot|null>(null)
  const [windowKey,setWindowKey]=useState<WindowKey>('24h')
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState('')
  const [detail,setDetail]=useState<Detail>(null)
  const [company,setCompany]=useState<Company|null>(null)
  const [tab,setTab]=useState(0)
  const load=useCallback(async()=>{
    setLoading(true);setError('')
    const response=await supabase.rpc('get_platform_control_center_snapshot',{target_window:windowKey})
    if(response.error)setError(response.error.message);else setData(response.data as Snapshot)
    setLoading(false)
  },[windowKey])
  useEffect(()=>{if(profile?.platform_role!=='admin')return;const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load,profile?.platform_role])
  const cards=useMemo(()=>data?[
    {label:'บริษัททั้งหมด',value:fmt(data.kpis.companies),sub:`ใช้งาน ${fmt(data.kpis.active_companies)}`,tone:'healthy',rows:data.companies.map(x=>({label:x.name,value:x.active?'ใช้งาน':'ระงับ',note:`สมาชิก ${x.members} · โครงการ ${x.projects} · ไซต์ ${x.sites}`}))},
    {label:'ผู้ใช้ / พนักงาน',value:`${fmt(data.kpis.users)} / ${fmt(data.kpis.employees)}`,sub:`พร้อม ${fmt(data.kpis.ready_employees)} · ขาดข้อมูล ${fmt(data.kpis.unready_employees)}`,tone:data.kpis.unready_employees?'warning':'healthy',rows:pairs(data.workforce,{ready:'พร้อมลงเวลา',missing_name:'ไม่มีชื่อ',missing_employment:'ไม่มีข้อมูลจ้าง',missing_pay_rate:'ไม่มีค่าจ้าง',missing_policy:'ไม่มีนโยบาย',missing_site:'ไม่มีไซต์',multi_site:'หลายไซต์'})},
    {label:'โครงการ / ไซต์',value:`${fmt(data.kpis.projects)} / ${fmt(data.kpis.sites)}`,sub:'ทุกบริษัท',tone:'healthy',rows:data.companies.map(x=>({label:x.name,value:`${x.projects} / ${x.sites}`,note:'โครงการ / ไซต์'}))},
    {label:'LINE / Telegram',value:`${fmt(data.kpis.line_groups)} / ${fmt(data.kpis.telegram_chats)}`,sub:`ข้อความ ${fmt(data.communication.line_messages)}`,tone:data.communication.telegram_failed?'warning':'healthy',rows:pairs(data.communication,{line_messages:'ข้อความ LINE',line_redeliveries:'LINE ส่งซ้ำ',line_quiet_24h:'กลุ่มเงียบ 24 ชม.',line_quiet_72h:'กลุ่มเงียบ 72 ชม.',telegram_processed:'Telegram สำเร็จ',telegram_failed:'Telegram ล้มเหลว'})},
    {label:'Error เปิดอยู่',value:fmt(data.kpis.open_errors),sub:`พบใน ${windows[windowKey]} ${fmt(data.kpis.errors_in_window)}`,tone:data.kpis.open_errors?'critical':'healthy',rows:data.errors.map(x=>({label:String(x.title),value:String(x.status),note:`${String(x.affected_module??'ไม่ระบุโมดูล')} · ${String(x.fingerprint??'ไม่มี Fingerprint')}`}))},
    {label:'งานค้าง / รออนุมัติ',value:`${fmt(data.kpis.pending_work)} / ${fmt(data.kpis.review_work)}`,sub:'ทะเบียนงานระบบกลาง',tone:data.kpis.review_work?'warning':'healthy',rows:data.work_items.map(x=>({label:`${String(x.work_key)} · ${String(x.title)}`,value:`${String(x.status)} ${String(x.progress)}%`,note:String(x.current_step??'ไม่ระบุขั้นตอน')}))},
    {label:'Worker ทำงาน',value:fmt(data.kpis.running_workers),sub:'Heartbeat ไม่เกิน 15 นาที',tone:data.kpis.running_workers?'healthy':'unknown',rows:[{label:'Worker ที่ยังมี heartbeat',value:fmt(data.kpis.running_workers),note:'ไม่รวม lease หมดอายุ'}]},
    {label:'เฉลี่ย / P95',value:`${fmt(data.kpis.avg_latency_ms)} / ${fmt(data.kpis.p95_latency_ms)} ms`,sub:`เฉพาะ ${windows[windowKey]}`,tone:data.kpis.p95_latency_ms>1000?'warning':'healthy',rows:data.top_slow.map(x=>({label:String(x.name),value:`${fmt(Number(x.latency_ms))} ms`,note:String(x.module)}))},
  ]:[],[data,windowKey])
  if(loading)return <Box sx={{minHeight:'60vh',display:'grid',placeItems:'center'}}><CircularProgress/></Box>
  if(error)return <Alert severity="warning">ไม่สามารถอ่าน Snapshot กลางได้: {error}</Alert>
  if(!data)return <Alert severity="info">ยังไม่มีข้อมูลสรุปกลาง</Alert>
  return <Stack spacing={2}>
    <Stack direction={{xs:'column',md:'row'}} sx={{gap:1,justifyContent:'space-between'}}>
      <Box><Typography variant="h4" sx={{fontWeight:900}}>ศูนย์จัดการระบบกลาง</Typography><Typography color="text.secondary">Platform Mode · ทุกบริษัท · อัปเดต {new Date(data.generated_at).toLocaleString('th-TH')}</Typography></Box>
      <Stack direction="row" spacing={1}><TextField select size="small" label="ช่วงข้อมูล" value={windowKey} onChange={e=>setWindowKey(e.target.value as WindowKey)} sx={{minWidth:145}}>{Object.entries(windows).map(([value,label])=><MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField><Button variant="contained" onClick={()=>void load()}>รีเฟรช</Button></Stack>
    </Stack>
    <Alert severity="info">ข้อมูลรวมสำหรับ Platform Admin เท่านั้น การเลือก Tenant ต้องยืนยันและไม่มีบริษัทเริ่มต้นที่ถูกเลือกแทนโดยอัตโนมัติ</Alert>
    <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,1fr)',lg:'repeat(4,1fr)'},gap:1.25}}>{cards.map(card=><Paper key={card.label} variant="outlined" onClick={()=>setDetail({title:card.label,rows:card.rows})} sx={{p:1.6,minHeight:105,cursor:'pointer',borderTop:4,borderTopColor:colors[card.tone as keyof typeof colors]}}><Typography variant="caption">{card.label}</Typography><Typography variant="h4" sx={{fontWeight:900}}>{card.value}</Typography><Typography variant="caption" color="text.secondary">{card.sub}</Typography></Paper>)}</Box>
    <Tabs value={tab} onChange={(_,value)=>setTab(value)} variant="scrollable" allowScrollButtonsMobile><Tab label="ภาพรวม"/><Tab label="Error"/><Tab label="LINE / Telegram"/><Tab label="Workforce"/><Tab label="บริษัทและ Tenant"/><Tab label="งานและ Audit"/></Tabs>
    {tab===0&&<Overview data={data}/>} {tab===1&&<ErrorCenter data={data}/>} {tab===2&&<MetricPanel title="ศูนย์ LINE และ Telegram" rows={pairs(data.communication,{line_messages:'ข้อความ LINE',line_redeliveries:'Webhook ส่งซ้ำ',line_quiet_24h:'กลุ่มเงียบ 24 ชั่วโมง',line_quiet_72h:'กลุ่มเงียบ 72 ชั่วโมง',telegram_processed:'Telegram สำเร็จ',telegram_failed:'Telegram ล้มเหลว'})}/>} {tab===3&&<MetricPanel title="ความพร้อม Workforce" rows={pairs(data.workforce,{ready:'พร้อมลงเวลา',missing_name:'ไม่มีชื่อ',missing_employment:'ไม่มีข้อมูลจ้าง',missing_pay_rate:'ไม่มีค่าจ้าง',missing_policy:'ไม่มีนโยบาย',missing_site:'ไม่มีไซต์',multi_site:'พนักงานหลายไซต์',attendance_review:'Attendance รอตรวจ',wage_overrides:'Admin ปรับค่าจ้าง'})}/>} {tab===4&&<CompanyTree companies={data.companies} onSelect={setCompany}/>} {tab===5&&<WorkAudit data={data}/>} 
    <Paper variant="outlined" sx={{p:2}}><Typography variant="subtitle2" sx={{fontWeight:850}}>นิยามข้อมูลและความสดใหม่</Typography>{data.metric_definitions.map(item=><Typography key={item.key} variant="caption" sx={{display:'block'}}><b>{item.label}:</b> {item.definition}</Typography>)}</Paper>
    <Dialog open={Boolean(detail)} onClose={()=>setDetail(null)} fullWidth maxWidth="md"><DialogTitle>{detail?.title}</DialogTitle><DialogContent><Stack divider={<Divider/>}>{detail?.rows.length?detail.rows.map((row,index)=><Box key={index} sx={{py:1}}><Stack direction="row" sx={{justifyContent:'space-between',gap:2}}><Typography sx={{fontWeight:750}}>{row.label}</Typography><Typography>{row.value}</Typography></Stack>{row.note&&<Typography variant="caption" color="text.secondary">{row.note}</Typography>}</Box>):<Typography color="text.secondary">ไม่มีรายการในช่วงที่เลือก</Typography>}</Stack></DialogContent><DialogActions><Button onClick={()=>setDetail(null)}>ปิด</Button></DialogActions></Dialog>
    <Dialog open={Boolean(company)} onClose={()=>setCompany(null)}><DialogTitle>ยืนยันเลือกบริษัท</DialogTitle><DialogContent><Alert severity="warning">เปลี่ยนบริบทไปยัง “{company?.name}” และโหลดสิทธิ์ใหม่ การดำเนินการนี้จะถูกบันทึกโดยระบบ</Alert></DialogContent><DialogActions><Button onClick={()=>setCompany(null)}>ยกเลิก</Button><Button variant="contained" onClick={()=>company&&void switchCompany(company.id)}>ยืนยัน</Button></DialogActions></Dialog>
  </Stack>
}

function Overview({data}:{data:Snapshot}){return <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'1.35fr 1fr'},gap:1.5}}><Paper variant="outlined" sx={{p:2}}><Typography variant="h6" sx={{fontWeight:850}}>Service Health Map</Typography><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,1fr)',md:'repeat(3,1fr)'},gap:1,mt:1}}>{data.health.map((item,index)=>{const status=String(item.status??'unknown');return <Box key={index} sx={{p:1.2,border:1,borderColor:colors[status as keyof typeof colors]??colors.unknown,borderRadius:2}}><Stack direction="row" sx={{justifyContent:'space-between'}}><Typography sx={{fontWeight:800}}>{String(item.name)}</Typography><Chip size="small" label={status}/></Stack><Typography variant="caption">{String(item.module)} · {String(item.latency_ms??'-')} ms · {String(item.tenant_count??0)} Tenant</Typography><Typography variant="body2">{String(item.message??'ไม่มีรายละเอียด')}</Typography></Box>})}</Box></Paper><Paper variant="outlined" sx={{p:2}}><Typography variant="h6" sx={{fontWeight:850}}>แนวโน้ม {windows[data.window]}</Typography><Stack direction="row" spacing={.45} sx={{height:180,mt:2,alignItems:'end'}}>{data.trend.map((point,index)=>{const total=Math.max(1,point.healthy+point.warning+point.critical);const height=Math.max(8,(point.healthy+point.warning+point.critical)/Math.max(...data.trend.map(x=>x.healthy+x.warning+x.critical),1)*160);return <Box key={index} title={`${new Date(point.bucket).toLocaleString('th-TH')} · ปกติ ${point.healthy} · เตือน ${point.warning} · วิกฤต ${point.critical}`} sx={{flex:1,height,bgcolor:point.critical?colors.critical:point.warning?colors.warning:colors.healthy,borderRadius:'4px 4px 0 0',opacity:Math.max(.45,total/(total+1))}}/>})}</Stack><Stack direction="row" spacing={2} sx={{mt:1}}><Typography variant="caption" color="success.main">● ปกติ</Typography><Typography variant="caption" color="warning.main">● เฝ้าระวัง</Typography><Typography variant="caption" color="error.main">● วิกฤต</Typography></Stack></Paper><MetricPanel title="Top 10 จุดที่ช้าที่สุด" rows={data.top_slow.map(x=>({label:`${String(x.module)} · ${String(x.name)}`,value:`${fmt(Number(x.latency_ms))} ms`,note:new Date(String(x.checked_at)).toLocaleString('th-TH')}))}/></Box>}
function ErrorCenter({data}:{data:Snapshot}){return <Stack spacing={1.5}><MetricPanel title="สถิติ Error" rows={pairs(data.error_summary,{open:'เปิดอยู่',monitoring:'กำลังติดตาม',resolved:'ปิดในช่วงที่เลือก',critical:'วิกฤต',system_occurrences:'ระบบตรวจพบ',user_reports:'ผู้ใช้ยืนยัน'})}/><ListPanel title="รายละเอียด Error และหลักฐาน" empty="ไม่มี Error ในช่วงที่เลือก" rows={data.errors.map(x=>({title:String(x.title),sub:`${String(x.affected_module??'ไม่ระบุ')} · Fingerprint ${String(x.fingerprint)} · ระบบ ${String(x.system_occurrence_count)} · ผู้ใช้ ${String(x.user_report_count)}`,tag:`${String(x.severity)} · ${String(x.status)}`}))}/></Stack>}
function CompanyTree({companies,onSelect}:{companies:Company[];onSelect:(company:Company)=>void}){return <Paper variant="outlined" sx={{p:2}}><Typography variant="h6" sx={{fontWeight:850}}>บริษัท → โครงการ → ไซต์ → พนักงาน</Typography>{companies.map(company=><Accordion key={company.id} disableGutters><AccordionSummary expandIcon={<ExpandMoreOutlinedIcon/>}><Stack direction={{xs:'column',sm:'row'}} sx={{justifyContent:'space-between',width:'100%',pr:1}}><Typography sx={{fontWeight:850}}>{company.name}</Typography><Typography variant="caption">พนักงาน {company.employees} · ขาดข้อมูล {company.unready} · โครงการ {company.projects} · ไซต์ {company.sites}</Typography></Stack></AccordionSummary><AccordionDetails><Stack spacing={1}>{company.children.map(project=><Paper key={project.id} variant="outlined" sx={{p:1.2}}><Typography sx={{fontWeight:800}}>{project.code?`${project.code} · `:''}{project.name}</Typography>{project.sites.map(site=><Typography key={site.id} variant="body2">↳ {site.name} · {site.active?'ใช้งาน':'ปิด'} · พนักงาน {site.employees}</Typography>)}{!project.sites.length&&<Typography variant="body2" color="warning.main">ยังไม่มีไซต์</Typography>}</Paper>)}<Button size="small" onClick={()=>onSelect(company)}>เลือกบริษัทนี้เพื่อจัดการ</Button></Stack></AccordionDetails></Accordion>)}</Paper>}
function WorkAudit({data}:{data:Snapshot}){return <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'1fr 1fr'},gap:1.5}}><ListPanel title="งานค้างและคำขออนุมัติ" empty="ไม่มีงานค้าง" rows={data.work_items.map(x=>({title:`${String(x.work_key)} · ${String(x.title)}`,sub:`${String(x.current_step??'ไม่ระบุขั้นตอน')} · Production ${String(x.production_status??'-')}`,tag:`${String(x.status)} ${String(x.progress)}%`}))}/><ListPanel title="Audit Timeline กลาง" empty="ยังไม่มีเหตุการณ์" rows={data.audit.map(x=>({title:`${String(x.source)} · ${String(x.event)}`,sub:`${String(x.reference)} · ${new Date(String(x.at)).toLocaleString('th-TH')}`}))}/></Box>}
function MetricPanel({title,rows}:{title:string;rows:Array<{label:string;value:string;note?:string}>}){return <Paper variant="outlined" sx={{p:2}}><Typography variant="h6" sx={{fontWeight:850}}>{title}</Typography><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,1fr)',lg:'repeat(3,1fr)'},gap:1,mt:1}}>{rows.map((row,index)=><Paper key={index} variant="outlined" sx={{p:1.25}}><Typography variant="caption">{row.label}</Typography><Typography variant="h6" sx={{fontWeight:850}}>{row.value}</Typography>{row.note&&<Typography variant="caption" color="text.secondary">{row.note}</Typography>}</Paper>)}</Box></Paper>}
function ListPanel({title,empty,rows}:{title:string;empty:string;rows:Array<{title:string;sub:string;tag?:string}>}){return <Paper variant="outlined" sx={{p:2}}><Typography variant="h6" sx={{fontWeight:850}}>{title}</Typography><Stack divider={<Divider/>}>{rows.slice(0,20).map((row,index)=><Box key={index} sx={{py:1}}><Stack direction="row" sx={{justifyContent:'space-between',gap:1}}><Typography sx={{fontWeight:750}}>{row.title}</Typography>{row.tag&&<Chip size="small" label={row.tag}/>}</Stack><Typography variant="caption">{row.sub}</Typography></Box>)}{!rows.length&&<Typography color="text.secondary" sx={{py:2}}>{empty}</Typography>}</Stack></Paper>}
