import {Alert,Button,Chip,FormControlLabel,MenuItem,Paper,Stack,Switch,TextField,Typography} from '@mui/material'
import {useCallback,useEffect,useState} from 'react'
import {PageHeader} from '../../components/PageHeader'
import {useAuth} from '../../hooks/useAuth'
import {usePageTitle} from '../../hooks/usePageTitle'
import {supabase} from '../../lib/supabase'

const roles={company_admin:'ผู้ดูแลบริษัท',executive:'ผู้บริหาร',manager:'ผู้จัดการ',site_supervisor:'ผู้ควบคุมไซต์',accounting_hr:'บัญชี/บุคคล',employee:'พนักงาน'}
type Member={profile_id:string;company_role:keyof typeof roles;member_type:'admin_only'|'employee'|'admin_employee';profiles:{full_name:string|null;email:string|null}|null}

export function SettingsPage(){
  usePageTitle('ตั้งค่าระบบ')
  const {companies,currentCompany,profile}=useAuth()
  const isPlatformAdmin=profile?.platform_role==='admin'
  const [company,setCompany]=useState({name:'',slug:''}),[member,setMember]=useState({email:'',role:'employee'})
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
  const [members,setMembers]=useState<Member[]>([])
  const loadMembers=useCallback(async()=>{if(!currentCompany)return;const {data,error:loadError}=await supabase.from('company_members').select('profile_id,company_role,member_type,profiles(full_name,email)').eq('company_id',currentCompany.company_id).eq('active',true).order('created_at');if(loadError)setError(loadError.message);else setMembers((data??[]) as unknown as Member[])},[currentCompany])
  useEffect(()=>{const timer=window.setTimeout(()=>void loadMembers(),0);return()=>window.clearTimeout(timer)},[loadMembers])
  const run=async(action:()=>Promise<{error:unknown}>,message:string)=>{setBusy(true);setError('');setSuccess('');const result=await action();if(result.error)setError(String((result.error as {message?:string}).message??result.error));else{setSuccess(message);window.setTimeout(()=>window.location.reload(),700)}setBusy(false)}
  return <Stack spacing={2.5}>
    <PageHeader title="บริษัทและสิทธิ์ใช้งาน" description="แยกข้อมูล สมาชิก บทบาท โครงการ และการตั้งค่าของแต่ละบริษัท"/>
    {error&&<Alert severity="error">{error}</Alert>}{success&&<Alert severity="success">{success}</Alert>}
    <Paper variant="outlined" sx={{p:2.5}}><Typography variant="h6">บริษัทที่เข้าใช้งานได้</Typography><Stack spacing={1} sx={{mt:1.5}}>{companies.map(item=><Stack key={item.company_id} direction="row" spacing={1} sx={{justifyContent:'space-between',alignItems:'center'}}><Typography>{item.company_name}{item.is_active?' · กำลังใช้งาน':''}</Typography><Typography color="text.secondary">{roles[item.company_role]??item.company_role}</Typography></Stack>)}</Stack></Paper>
    <Paper variant="outlined" sx={{p:2.5}}><Typography variant="h6">เพิ่มบริษัท</Typography><Alert severity={isPlatformAdmin?'info':'warning'} sx={{my:1.5}}>{isPlatformAdmin?'เฉพาะ Platform Admin: ผู้สร้างจะเป็นผู้ดูแลบริษัทใหม่ และระบบจะแยกข้อมูลจากบริษัทเดิมทันที':'เฉพาะ Platform Admin เท่านั้นที่สร้างบริษัทใหม่ได้'}</Alert><Stack direction={{xs:'column',md:'row'}} spacing={1.5}><TextField disabled={!isPlatformAdmin} label="ชื่อบริษัท" value={company.name} onChange={event=>setCompany({...company,name:event.target.value})}/><TextField disabled={!isPlatformAdmin} label="รหัสบริษัท" helperText="ภาษาอังกฤษ ตัวเลข และขีดกลาง เช่น tec-01" value={company.slug} onChange={event=>setCompany({...company,slug:event.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'')})}/><Button variant="contained" disabled={busy||!isPlatformAdmin||!company.name.trim()||!company.slug.trim()} onClick={()=>void run(async()=>supabase.rpc('create_company',{company_name:company.name,company_slug:company.slug}),'สร้างบริษัทแล้ว')}>สร้างบริษัท</Button></Stack></Paper>
    <Paper variant="outlined" sx={{p:2.5}}><Typography variant="h6">เพิ่มสมาชิกใน {currentCompany?.company_name??'บริษัทปัจจุบัน'}</Typography><Stack direction={{xs:'column',md:'row'}} spacing={1.5} sx={{mt:1.5}}><TextField type="email" label="อีเมลบัญชีที่มีอยู่" value={member.email} onChange={event=>setMember({...member,email:event.target.value})}/><TextField select label="บทบาท" value={member.role} onChange={event=>setMember({...member,role:event.target.value})}>{Object.entries(roles).map(([value,label])=><MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField><Button variant="contained" disabled={busy||!member.email.trim()} onClick={()=>void run(async()=>supabase.rpc('add_company_member',{member_email:member.email,member_role:member.role}),'เพิ่มสมาชิกบริษัทแล้ว')}>เพิ่มสมาชิก</Button></Stack></Paper>
    <Paper variant="outlined" sx={{p:2.5}}><Typography variant="h6">สมาชิกและสถานะพนักงาน</Typography><Typography color="text.secondary">ผู้ดูแลที่ไม่ใช่พนักงานจะไม่ถูกตรวจความพร้อม ไม่อยู่ในระบบค่าจ้าง และลงเวลาไม่ได้</Typography><Stack spacing={1.5} sx={{mt:2}}>{members.map(item=>{const adminRole=['company_admin','executive','manager'].includes(item.company_role);const isEmployee=item.member_type!=='admin_only';return <Paper key={item.profile_id} variant="outlined" sx={{p:1.5}}><Stack direction={{xs:'column',md:'row'}} spacing={1} sx={{alignItems:{md:'center'},justifyContent:'space-between'}}><Stack><Typography sx={{fontWeight:700}}>{item.profiles?.full_name||item.profiles?.email||item.profile_id}</Typography><Stack direction="row" spacing={.75}><Chip size="small" label={roles[item.company_role]}/><Chip size="small" color={isEmployee?'success':'default'} label={isEmployee?'เป็นพนักงานบริษัท':'ผู้ดูแลเท่านั้น'}/></Stack></Stack><FormControlLabel control={<Switch checked={isEmployee} disabled={busy||!adminRole} onChange={event=>{const next=event.target.checked?'admin_employee':'admin_only';void run(async()=>supabase.rpc('update_company_member_type',{target_profile_id:item.profile_id,target_member_type:next,target_reason:event.target.checked?'กำหนดผู้ดูแลให้เป็นพนักงานบริษัทผ่านหน้าตั้งค่า':'กำหนดเป็นผู้ดูแลระบบที่ไม่ใช่พนักงานบริษัทผ่านหน้าตั้งค่า'}),event.target.checked?'เปิดสถานะพนักงานแล้ว':'ตั้งเป็นผู้ดูแลที่ไม่ใช่พนักงานแล้ว')}}/>} label="นับเป็นพนักงานของบริษัท"/></Stack></Paper>})}</Stack></Paper>
  </Stack>
}
