import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
const page = readFileSync('src/pages/AccountingDocuments/index.tsx', 'utf8')
const migration = readFileSync('supabase/migrations/20260823111848_transfer_slip_drawer_review.sql', 'utf8')
const lineageMigration = readFileSync('supabase/migrations/20260823122135_transfer_slip_money_lineage_routing.sql', 'utf8')
const allocationMigration = readFileSync('supabase/migrations/20260826220000_transfer_slip_money_allocations_v2.sql', 'utf8')
const edge = readFileSync('supabase/functions/reprocess-transfer-slips/index.ts', 'utf8')
assert.match(page, /1\. รูปต้นฉบับและ AI/)
assert.match(page, /2\. ตรวจและแก้ข้อมูล/)
for (const label of ['1. หลักฐานเดิมจากสลิป · อ่านอย่างเดียว', '2. ค่าที่อ่านจากหลักฐาน · Candidate สำหรับตรวจ', '3. ข้อมูลใช้งานจริงชุดเดียว · Canonical', 'SOURCE / ไม่เขียนทับ', 'ยังไม่มีข้อมูลยืนยัน']) assert.match(page, new RegExp(label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
assert.match(page, /transfer_slip_operational_truth_v1/)
assert.match(page, /ห้ามนำไปลงบัญชีก่อนยืนยัน/)
assert.match(page, /review_transfer_slip_money_lineage_v2/)
assert.match(page, /ให้ AI อ่านสลิปใหม่/)
assert.match(page, /onClick=\{\(\) => void openSlipDetail\(row\)\}/)
assert.match(migration, /transfer_slip_review_locked/)
assert.match(migration, /changed_fields/)
assert.match(migration, /before.*after/s)
assert.match(migration, /revoke all on function public\.review_transfer_slip_details/)
assert.match(lineageMigration, /transfer_slip_money_lineages/)
assert.match(lineageMigration, /transfer_slip_money_lineage_/)
assert.match(lineageMigration, /accounting_review/)
assert.match(page, /เส้นทางเอกสารและเส้นทางเงิน/)
assert.match(page, /ยืนยันการจัดสรรและส่งปลายทาง/)
assert.match(page, /การจัดสรรเงิน/)
assert.match(page, /เชื่อมจากเส้นเงินก่อนหน้า/)
assert.match(allocationMigration, /transfer_slip_money_allocations/)
assert.match(allocationMigration, /root_lineage_id/)
assert.match(allocationMigration, /parent_lineage_id/)
assert.match(allocationMigration, /money_allocation_not_reconciled/)
assert.match(allocationMigration, /allocation_before.*allocation_after/s)
assert.match(allocationMigration, /advance_allocation_must_be_exclusive/)
assert.match(allocationMigration, /transfer_slip_money_allocations_active_key_idx/)
assert.match(allocationMigration, /set status = 'superseded'/)
assert.match(allocationMigration, /max\(previous\.version\) \+ 1/)
assert.match(edge, /item_id\?: string/)
assert.match(edge, /transfer_slip_ai_reread/)
assert.match(edge, /single_item/)
assert.match(edge, /targetItemId \? item\.current_flow/)
console.log('accounting transfer-slip review contract: PASS')
