import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const claimMigrationPath = new URL('../supabase/migrations/202608090021_skip_unapproved_automation_work.sql', import.meta.url)
const recoveryMigrationPath = new URL('../supabase/migrations/202608090020_recover_stale_automation_work.sql', import.meta.url)
const runnerPath = new URL('./local-automation-runner.ps1', import.meta.url)
const healthMonitorPath = new URL('../supabase/functions/health-monitor/index.ts', import.meta.url)
const approvalMigrationPath = new URL('../supabase/migrations/202608110033_persistent_work_item_approval.sql', import.meta.url)
const specificClaimMigrationPath = new URL('../supabase/migrations/202608150003_atomic_specific_work_item_claim.sql', import.meta.url)
const automationWorkerPath = new URL('../supabase/functions/automation-worker/index.ts', import.meta.url)
const sql = readFileSync(claimMigrationPath, 'utf8')
const recoverySql = readFileSync(recoveryMigrationPath, 'utf8')
const runner = readFileSync(runnerPath, 'utf8')
const healthMonitor = readFileSync(healthMonitorPath, 'utf8')
const approvalSql = readFileSync(approvalMigrationPath, 'utf8')
const specificClaimSql = readFileSync(specificClaimMigrationPath, 'utf8')
const automationWorker = readFileSync(automationWorkerPath, 'utf8')

assert.match(sql, /where item\.status = 'ready'[\s\S]*coalesce\(item\.production_status, ''\) <> 'awaiting_approval'/)
assert.match(sql, /for update skip locked limit 1/)
assert.match(sql, /where item\.work_key = selected\.work_key/)
assert.doesNotMatch(sql, /where work_key\s*=\s*selected\.work_key/)
assert.match(sql, /returning id into selected_run/)

assert.match(recoverySql, /update public\.system_worker_runs as run[\s\S]*run\.status = 'running'[\s\S]*run\.heartbeat_at < stale_cutoff/)
assert.match(recoverySql, /update public\.system_work_items as item[\s\S]*item\.status = 'doing'[\s\S]*item\.worker_id is null[\s\S]*item\.heartbeat_at < stale_cutoff/)
assert.match(recoverySql, /not exists \([\s\S]*active_run\.status = 'running'[\s\S]*active_run\.heartbeat_at >= stale_cutoff/)
assert.match(recoverySql, /item\.status = 'blocked'[\s\S]*item\.evidence ilike '%--ask-for-approval%'/)
assert.match(recoverySql, /perform public\.recover_stale_system_work_items\(10\)/)

assert.match(runner, /action='heartbeat'[\s\S]*run_id=\$item\.run_id/)
assert.match(runner, /Start-Sleep -Seconds 60/)
assert.match(runner, /exec - --ephemeral --approve-for-me/)
assert.doesNotMatch(runner, /--ask-for-approval/)
assert.doesNotMatch(runner, /exec[^\r\n]*--sandbox/)
assert.match(runner, /\$hasMatchingApproval = \$item\.approval_status -eq 'approved'/)
assert.match(runner, /\$requiresApproval -and -not \$hasMatchingApproval/)

assert.match(approvalSql, /add column if not exists approval_fingerprint text/)
assert.match(approvalSql, /sync_system_work_item_approval_trigger/)
assert.match(approvalSql, /item\.approval_status = 'approved'/)
assert.match(approvalSql, /item\.approval_fingerprint = public\.system_work_item_scope_fingerprint/)
assert.match(approvalSql, /where work_key = 'AUD-001'/)
assert.match(approvalSql, /where work_key = 'TEN-003'/)

assert.match(specificClaimSql, /create or replace function public\.claim_specific_system_work_item/)
assert.match(specificClaimSql, /item\.production_status = 'approved_for_execution'/)
assert.match(specificClaimSql, /item\.approval_status = 'approved'/)
assert.match(specificClaimSql, /item\.approval_fingerprint = public\.system_work_item_scope_fingerprint/)
assert.match(specificClaimSql, /for update skip locked/)
assert.match(specificClaimSql, /insert into public\.system_worker_runs[\s\S]*returning id into selected_run/)
assert.match(specificClaimSql, /update public\.system_work_items as item[\s\S]*current_step = 'claimed_specific'/)
assert.match(specificClaimSql, /revoke all on function public\.claim_specific_system_work_item\(text, text, integer\) from public, anon, authenticated/)
assert.match(automationWorker, /admin\.rpc\('claim_specific_system_work_item'/)
assert.doesNotMatch(automationWorker, /const now = new Date\(\), runId = crypto\.randomUUID\(\)/)
assert.doesNotMatch(automationWorker, /admin\.from\('system_worker_runs'\)\.insert/)

assert.match(healthMonitor, /const failures = results\.filter\(result => result\.status !== 'healthy'\)/)
assert.match(healthMonitor, /const fingerprints = failures\.map\(result => `\$\{result\.module\}:\$\{result\.key\}`\)\.sort\(\)/)
assert.match(healthMonitor, /error_fingerprint: fingerprints\.join\('\|'\)\.slice\(0, 200\) \|\| null/)
assert.match(healthMonitor, /\.eq\('work_key', 'SYS-004'\)/)
assert.match(healthMonitor, /await updateErrorWorkItem\(results, now\)/)

console.log('automation claim, stale recovery, and SYS-004 aggregation regression tests passed')
