import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const migration = readFileSync('supabase/migrations/20260831072537_borrowed_fund_obligations.sql', 'utf8')
const manualMigration = readFileSync('supabase/migrations/20260831134117_manual_cash_receipt_pending_evidence.sql', 'utf8')
const page = readFileSync('src/pages/AccountingDocuments/index.tsx', 'utf8')
const service = readFileSync('src/services/transferSlipMoneyLineage.ts', 'utf8')

assert.match(migration, /'borrowed_funds'/)
assert.match(migration, /create table if not exists public\.borrowed_fund_obligations/)
assert.match(migration, /principal_amount numeric\(14,2\).*repaid_amount/s)
assert.match(migration, /status in \('outstanding','partially_repaid','repaid','cancelled'\)/)
assert.match(migration, /enable row level security/)
assert.match(migration, /revoke all on table public\.borrowed_fund_obligations from public, anon/)
assert.match(migration, /company_role='accounting_hr'/)
assert.match(migration, /workflow_permission_denied/)
assert.match(migration, /event_key=target_event_key/)
assert.match(migration, /borrowed_fund_obligation_recorded/)
assert.match(page, /เงินยืมจากบุคคล\/กรรมการ → ตั้งต้น\/เติมกองผู้รับ/)
assert.match(page, /record_borrowed_fund_obligation_v1/)
const advanceDraftCall = page.indexOf("saveBase('draft', `${eventKey}:advance-classification-draft`)")
const advanceObligationCall = page.indexOf('await recordBorrowedFundObligation(routeResult.lineage_id)')
const advanceConfirmCall = page.indexOf("saveBase('confirm', eventKey)")
assert.ok(advanceDraftCall >= 0 && advanceDraftCall < advanceObligationCall, 'obligation must follow the lineage draft')
assert.ok(advanceObligationCall < advanceConfirmCall, 'obligation must be recorded before final confirmation')
assert.match(service, /borrowed_funds.*loanLenderName/s)
assert.match(service, /กำหนดคืนเงินยืม/)
assert.match(manualMigration, /create table public\.manual_cash_receipts/)
assert.match(manualMigration, /pending_evidence/)
assert.match(manualMigration, /temporary_credit_account_code text not null default '2199'/)
assert.match(manualMigration, /create_manual_cash_receipt_v1/)
assert.match(manualMigration, /enable row level security/)
assert.match(page, /รับเงินสด\/เงินยืมเข้าบัญชี Manual/)
assert.match(page, /รับเงินไว้ก่อน/)

console.log('borrowed fund obligation contract passed')
