import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { normalizeAppBadgeCount } from '../src/services/appBadge.ts'

const router = readFileSync('src/router/index.tsx', 'utf8')
const launcher = readFileSync('src/pages/AppLauncher/index.tsx', 'utf8')
const unread = readFileSync('src/services/chatUnread.ts', 'utf8')
const appBadge = readFileSync('src/services/appBadge.ts', 'utf8')
const chat = readFileSync('src/pages/Chat/index.tsx', 'utf8')
const migration = readFileSync('supabase/migrations/20260822003747_chat_attachment_mobile_images.sql', 'utf8')
const timeTracking = readFileSync('src/pages/TimeTracking/index.tsx', 'utf8')
const mainLayout = readFileSync('src/layouts/MainLayout.tsx', 'utf8')

assert.match(router, /index: true, element: deferred\(<AppLauncherPage \/>\)/)
assert.match(launcher, /fetchChatUnreadCount/)
assert.match(launcher, /badgeContent=\{unreadCount > 99 \? '99\+' : unreadCount\}/)
assert.match(launcher, /syncAppBadge\(unreadCount\)/)
assert.match(launcher, /ข้อความยังไม่ได้อ่าน/)
assert.match(launcher, /navigate\('\/chat'\)/)
assert.match(launcher, /navigate\('\/time-tracking'\)/)
assert.match(unread, /chat_room_read_states/)
assert.match(unread, /chat_messages/)
assert.match(unread, /chat_room_members/)
assert.match(unread, /joined_at/)
assert.match(unread, /sender_profile_id\.is\.null/)
assert.match(unread, /deleted_at/)
assert.match(appBadge, /setAppBadge/)
assert.match(appBadge, /clearAppBadge/)
assert.match(appBadge, /Never block the in-app unread UI/)
assert.equal(normalizeAppBadgeCount(7.9), 7)
assert.equal(normalizeAppBadgeCount(-1), 0)
assert.equal(normalizeAppBadgeCount(Number.NaN), 0)
assert.equal(normalizeAppBadgeCount(1200), 999)
assert.match(chat, /image\/heic/)
assert.match(chat, /image\/heif/)
assert.match(chat, /getChatAttachmentContentType/)
assert.match(chat, /createChatAttachmentId/)
assert.match(chat, /fallback-\$\{Date\.now\(\)/)
assert.match(chat, /ยังไม่พร้อมส่งไฟล์/)
assert.match(chat, /ส่งไฟล์เรียบร้อยแล้ว/)
assert.match(chat, /pendingAttachment/)
assert.match(chat, /กำลังส่ง.*อัตโนมัติ/)
assert.match(chat, /void sendFileMessage\(file\)/)
assert.match(chat, /ตรวจสิทธิ์สมาชิกห้อง/)
assert.match(chat, /pendingAttachmentPreviewUrl/)
assert.match(chat, /ลองส่งอีกครั้ง/)
assert.match(chat, /เซสชันหมดอายุ/)
assert.match(chat, /sessionExpiresSoon/)
assert.match(chat, /refreshError/)
assert.match(chat, /42501/)
assert.match(chat, /row-level\|permission\|unauthorized/)
assert.match(chat, /invalid uuid/)
assert.match(chat, /uploadBody/)
assert.match(chat, /aria-label="เลือกไฟล์แนบ"/)
assert.match(chat, /handleChatDragEnter/)
assert.match(chat, /handleChatDragOver/)
assert.match(chat, /handleChatDrop/)
assert.match(chat, /dataTransfer\.files/)
assert.match(chat, /วางไฟล์ที่นี่/)
assert.match(chat, /ลากไฟล์มาวางในพื้นที่แชต/)
assert.match(chat, /isChatImageAttachment/)
assert.match(chat, /component="img"/)
assert.match(chat, /เปิดรูปเต็ม/)
assert.match(chat, /failedAttachmentPreviews/)
assert.match(chat, /wisdomai-chat-room:/)
assert.match(chat, /realtime\.setAuth\(accessToken\)/)
assert.match(chat, /realtimeAuthReady/)
assert.match(chat, /accept="image\/\*,\.heic,\.heif,\.avif/)
assert.match(chat, /component="label"/)
assert.match(chat, /chat_attachment_picker_opened/)
assert.match(chat, /chat_attachment_file_selected/)
assert.match(chat, /chat_attachment_send_started/)
assert.match(chat, /chat_attachment_message_recorded/)
assert.match(chat, /event\.currentTarget\.value = ''/)
assert.doesNotMatch(chat, /setToast\(`กำลังส่ง \$\{file\.name\} อัตโนมัติ…`\)\s+if \(fileInputRef\.current\) fileInputRef\.current\.value = ''/)
assert.match(migration, /image\/heic/)
assert.match(migration, /image\/heif/)
assert.doesNotMatch(timeTracking, /aria-label="เปิด Web Chat"/)
assert.match(timeTracking, /ลงเวลาของฉัน/)
assert.match(timeTracking, /พร้อมตรวจ GPS/)
assert.match(timeTracking, /Selfie เมื่อกด/)
assert.match(timeTracking, /เวลาเข้า/)
assert.match(timeTracking, /เวลาออก/)
assert.match(mainLayout, /location\.pathname === '\/'/)
assert.match(mainLayout, /!isLauncher && <Sidebar \/>/)

console.log('chat launcher unread badge and mobile attachment checks passed')
