import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { normalizeAppBadgeCount } from '../src/services/appBadge.ts'

const router = readFileSync('src/router/index.tsx', 'utf8')
const launcher = readFileSync('src/pages/AppLauncher/index.tsx', 'utf8')
const unread = readFileSync('src/services/chatUnread.ts', 'utf8')
const appBadge = readFileSync('src/services/appBadge.ts', 'utf8')
const chat = readFileSync('src/pages/Chat/index.tsx', 'utf8')
const attachmentDraft = readFileSync('src/services/chatAttachmentDraft.ts', 'utf8')
const migration = readFileSync('supabase/migrations/20260822003747_chat_attachment_mobile_images.sql', 'utf8')
const timeTracking = readFileSync('src/pages/TimeTracking/index.tsx', 'utf8')
const mainLayout = readFileSync('src/layouts/MainLayout.tsx', 'utf8')

assert.match(router, /index: true, element: deferred\(<AppLauncherPage \/>\)/)
assert.match(launcher, /fetchChatUnreadCount/)
assert.match(launcher, /badgeContent=\{unreadCount > 99 \? '99\+' : unreadCount\}/)
assert.match(launcher, /syncAppBadge\(unreadCount\)/)
assert.match(launcher, /ข้อความยังไม่ได้อ่าน/)
assert.match(launcher, /navigate\('\/chat'\)/)
assert.match(launcher, /navigate\('\/time-tracking'\)/)
assert.match(unread, /chat_room_read_states/)
assert.match(unread, /chat_messages/)
assert.match(unread, /chat_room_members/)
assert.match(unread, /joined_at/)
assert.match(unread, /sender_profile_id\.is\.null/)
assert.match(unread, /deleted_at/)
assert.match(appBadge, /setAppBadge/)
assert.match(appBadge, /clearAppBadge/)
assert.match(appBadge, /Never block the in-app unread UI/)
assert.equal(normalizeAppBadgeCount(7.9), 7)
assert.equal(normalizeAppBadgeCount(-1), 0)
assert.equal(normalizeAppBadgeCount(Number.NaN), 0)
assert.equal(normalizeAppBadgeCount(1200), 999)
assert.match(chat, /image\/heic/)
assert.match(chat, /image\/heif/)
assert.match(chat, /getChatAttachmentContentType/)
assert.match(chat, /createChatAttachmentId/)
assert.match(chat, /fallback-\$\{Date\.now\(\)/)
assert.match(chat, /ยังไม่พร้อมส่งไฟล์/)
assert.match(chat, /ส่งไฟล์เรียบร้อยแล้ว/)
assert.match(chat, /pendingAttachment/)
assert.match(chat, /PendingAttachmentStatus = 'ready' \| 'uploading' \| 'failed'/)
assert.match(chat, /chat_attachment_waiting_confirmation/)
assert.match(chat, /chat_attachment_draft_persisted/)
assert.match(chat, /chat_attachment_draft_restored/)
assert.match(chat, /saveChatAttachmentDraft/)
assert.match(chat, /loadChatAttachmentDraft/)
assert.match(chat, /removeChatAttachmentDraft/)
assert.match(chat, /draft_persisted: draftPersisted/)
assert.match(chat, /กรุณาตรวจ Preview และกดส่ง/)
assert.match(chat, /label=\{pendingAttachmentStatus === 'failed' \? 'ส่งไม่สำเร็จ'/)
assert.match(chat, /pendingAttachmentPreviewUrl \? 'ส่งรูป' : 'ส่งไฟล์'/)
assert.match(chat, /onClick=\{\(\) => void sendFileMessage\(pendingAttachment\)\}/)
assert.doesNotMatch(chat, /กำลังส่ง.*อัตโนมัติ/)
assert.doesNotMatch(chat, /void sendFileMessage\(file\)\s*\n\s*\}/)
assert.match(chat, /pendingAttachmentRoomId !== selectedRoom\.id/)
assert.match(chat, /ป้องกันการส่งผิดห้อง/)
assert.match(attachmentDraft, /indexedDB\.open\(chatAttachmentDraftDatabase, chatAttachmentDraftVersion\)/)
assert.match(attachmentDraft, /database\.createObjectStore\(chatAttachmentDraftStore, \{ keyPath: 'key' \}\)/)
assert.match(attachmentDraft, /blob: file\.slice\(0, file\.size/)
assert.match(attachmentDraft, /chatAttachmentDraftTtlMs = 30 \* 60 \* 1000/)
assert.match(attachmentDraft, /return new File\(\[record\.blob\], record\.name/)
assert.match(attachmentDraft, /await removeChatAttachmentDraft\(scope\)/)
assert.match(chat, /ตรวจสิทธิ์สมาชิกห้อง/)
assert.match(chat, /pendingAttachmentPreviewUrl/)
assert.match(chat, /ลองส่งอีกครั้ง/)
assert.match(chat, /เซสชันหมดอายุ/)
assert.match(chat, /sessionExpiresSoon/)
assert.match(chat, /refreshError/)
assert.match(chat, /42501/)
assert.match(chat, /row-level\|permission\|unauthorized/)
assert.match(chat, /invalid uuid/)
assert.match(chat, /uploadBody/)
assert.match(chat, /aria-label="แนบรูปหรือไฟล์"/)
assert.match(chat, /handleChatDragEnter/)
assert.match(chat, /handleChatDragOver/)
assert.match(chat, /handleChatDrop/)
assert.match(chat, /dataTransfer\.files/)
assert.match(chat, /วางไฟล์ที่นี่/)
assert.match(chat, /ลากไฟล์มาวางในพื้นที่แชต/)
assert.match(chat, /isChatImageAttachment/)
assert.match(chat, /component="img"/)
assert.match(chat, /เปิดรูปเต็ม/)
assert.match(chat, /failedAttachmentPreviews/)
assert.match(chat, /wisdomai-chat-room:/)
assert.match(chat, /realtime\.setAuth\(accessToken\)/)
assert.match(chat, /realtimeAuthReady/)
assert.match(chat, /accept="image\/jpeg,image\/png,image\/webp,image\/heic/)
assert.doesNotMatch(chat, /component="label"/)
assert.match(chat, /aria-label="แนบรูปหรือไฟล์"/)
assert.match(chat, /aria-label="เลือกไฟล์แบบสำรอง"/)
assert.match(chat, /style=\{\{ display: 'none' \}\}/)
assert.match(chat, /onInput=\{\(event\) => handleAttachmentInputEvent\(event\.currentTarget, 'input'\)\}/)
assert.match(chat, /onChange=\{\(event\) => handleAttachmentInputEvent\(event\.currentTarget, 'change'\)\}/)
assert.match(chat, /const handleAttachmentPickerPointerDown = \(\) =>/)
assert.match(chat, /const openFileSystemAttachmentPicker = async \(\) =>/)
assert.match(chat, /showOpenFilePicker/)
assert.match(chat, /picker\.call\(window, \{ multiple: false \}\)/)
assert.match(chat, /const startAttachmentCamera = async \(\) =>/)
assert.match(chat, /navigator\.mediaDevices\.getUserMedia/)
assert.match(chat, /facingMode: \{ ideal: 'environment' \}/)
assert.match(chat, /canvas\.toBlob\(resolve, 'image\/jpeg', 0\.82\)/)
assert.match(chat, /ถ่ายรูปในแอป/)
assert.match(chat, /ใช้รูปนี้/)
assert.match(chat, /เลือกไฟล์แบบสำรอง/)
assert.match(chat, /chat_attachment_camera_ready/)
assert.match(chat, /const handleAttachmentInputEvent = \(input: HTMLInputElement, source: 'input' \| 'change'\) =>/)
assert.match(chat, /lastHandledAttachmentSelectionRef/)
assert.match(chat, /if \(fileInputRef\.current\) fileInputRef\.current\.value = ''/)
assert.match(chat, /chat_attachment_picker_opened/)
assert.match(chat, /chat_attachment_file_received/)
assert.match(chat, /chat_attachment_file_selected/)
assert.match(chat, /chat_attachment_selection_blocked/)
assert.match(chat, /reason: 'not_ready'/)
assert.match(chat, /reason: 'file_too_large'/)
assert.match(chat, /reason: 'unsupported_type'/)
assert.match(chat, /chat_attachment_send_started/)
assert.match(chat, /chat_attachment_message_recorded/)
assert.doesNotMatch(chat, /onClick=\{\(event\) => \{\s*\/\/ Reset before opening the native picker/)
assert.doesNotMatch(chat, /setToast\(`กำลังส่ง \$\{file\.name\} อัตโนมัติ…`\)\s+if \(fileInputRef\.current\) fileInputRef\.current\.value = ''/)
assert.match(migration, /image\/heic/)
assert.match(migration, /image\/heif/)
assert.doesNotMatch(timeTracking, /aria-label="เปิด Web Chat"/)
assert.match(timeTracking, /ลงเวลาของฉัน/)
assert.match(timeTracking, /พร้อมตรวจ GPS/)
assert.match(timeTracking, /Selfie เมื่อกด/)
assert.match(timeTracking, /เวลาเข้า/)
assert.match(timeTracking, /เวลาออก/)
assert.match(mainLayout, /location\.pathname === '\/'/)
assert.match(mainLayout, /!isLauncher && <Sidebar \/>/)

console.log('chat launcher unread badge and mobile attachment checks passed')
