import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const router = readFileSync('src/router/index.tsx', 'utf8')
const launcher = readFileSync('src/pages/AppLauncher/index.tsx', 'utf8')
const unread = readFileSync('src/services/chatUnread.ts', 'utf8')
const chat = readFileSync('src/pages/Chat/index.tsx', 'utf8')
const migration = readFileSync('supabase/migrations/20260822003747_chat_attachment_mobile_images.sql', 'utf8')
const timeTracking = readFileSync('src/pages/TimeTracking/index.tsx', 'utf8')
const mainLayout = readFileSync('src/layouts/MainLayout.tsx', 'utf8')

assert.match(router, /index: true, element: deferred\(<AppLauncherPage \/>\)/)
assert.match(launcher, /fetchChatUnreadCount/)
assert.match(launcher, /badgeContent=\{unreadCount > 99 \? '99\+' : unreadCount\}/)
assert.match(launcher, /navigate\('\/chat'\)/)
assert.match(launcher, /navigate\('\/time-tracking'\)/)
assert.match(unread, /chat_room_read_states/)
assert.match(unread, /chat_messages/)
assert.match(chat, /image\/heic/)
assert.match(chat, /image\/heif/)
assert.match(chat, /getChatAttachmentContentType/)
assert.match(chat, /createChatAttachmentId/)
assert.match(chat, /fallback-\$\{Date\.now\(\)/)
assert.match(chat, /ยังไม่พร้อมส่งไฟล์/)
assert.match(chat, /ส่งไฟล์เรียบร้อยแล้ว/)
assert.match(chat, /pendingAttachment/)
assert.match(chat, /เลือกไฟล์.*แล้ว กดปุ่มส่ง/)
assert.match(chat, /เซสชันหมดอายุ/)
assert.match(chat, /sessionExpiresSoon/)
assert.match(chat, /refreshError/)
assert.match(chat, /42501/)
assert.match(chat, /row-level\|permission\|unauthorized/)
assert.match(chat, /invalid uuid/)
assert.match(chat, /uploadBody/)
assert.match(chat, /aria-label="เลือกไฟล์แนบ"/)
assert.match(chat, /handleChatDragEnter/)
assert.match(chat, /handleChatDragOver/)
assert.match(chat, /handleChatDrop/)
assert.match(chat, /dataTransfer\.files/)
assert.match(chat, /วางไฟล์ที่นี่/)
assert.match(chat, /ลากไฟล์มาวางในพื้นที่แชต/)
assert.match(chat, /wisdomai-chat-room:/)
assert.match(chat, /realtime\.setAuth\(accessToken\)/)
assert.match(chat, /realtimeAuthReady/)
assert.match(chat, /accept="image\/\*,\.heic,\.heif,\.avif/)
assert.match(migration, /image\/heic/)
assert.match(migration, /image\/heif/)
assert.match(timeTracking, /aria-label="เปิด Web Chat"/)
assert.match(mainLayout, /location\.pathname === '\/'/)
assert.match(mainLayout, /!isLauncher && <Sidebar \/>/)

console.log('chat launcher unread badge and mobile attachment checks passed')
