import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const migration = readFileSync('supabase/migrations/20260907130000_control_plane_stall_recovery.sql', 'utf8')
const worker = readFileSync('supabase/functions/automation-worker/index.ts', 'utf8')
const runner = readFileSync('scripts/local-automation-runner.ps1', 'utf8')
const schema = readFileSync('scripts/automation-result.schema.json', 'utf8')
const page = readFileSync('src/pages/WorkCommandCenter/index.tsx', 'utf8')

assert.match(migration, /add column if not exists worker_outcome text/)
assert.match(migration, /add column if not exists outcome_reason text/)
assert.match(migration, /submit_system_work_item_for_review/)
assert.match(migration, /submission_reason_required/)
assert.match(migration, /reconcile_approved_system_work_item_execution/)
assert.match(migration, /approval_scope_fingerprint_mismatch/)
assert.match(migration, /active_worker_lease_present/)
assert.match(migration, /retry_cap_requires_explicit_reset/)
assert.match(migration, /for update skip locked/)
assert.match(migration, /outcome='no_output'/)
assert.match(migration, /target_outcome text default null/)
assert.match(migration, /completed_outcome_required/)
assert.match(migration, /blocked_or_no_output_required/)
assert.match(migration, /grant execute on function public\.reconcile_approved_system_work_item_execution\(text,text,text\) to authenticated/)
assert.doesNotMatch(worker, /action === 'approve_review'/)
assert.match(worker, /terminal_outcome_and_reason_required/)
assert.match(worker, /target_outcome: body\.outcome/)
assert.match(runner, /'no_output' 'Codex CLI ended without a schema-valid terminal result\.'/)
assert.match(runner, /Always provide outcome and outcome_reason/)
assert.match(schema, /"outcome"/)
assert.match(schema, /"outcome_reason"/)
assert.match(page, /submit_system_work_item_for_review/)
assert.match(page, /reconcile_approved_system_work_item_execution/)
assert.match(page, /ผลลัพธ์ worker ล่าสุด/)
assert.doesNotMatch(page, /\.from\("system_work_items"\)\s*\.update/)

console.log('control-plane stall recovery contract checks passed')
