import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const migration = readFileSync('supabase/migrations/20260825203000_employee_intake_preboarding_draft.sql', 'utf8')
const updateMigration = readFileSync('supabase/migrations/20260825212911_employee_intake_preboarding_update.sql', 'utf8')
const siteAssignmentMigration = readFileSync('supabase/migrations/20260825231500_employee_drawer_site_assignment_audit.sql', 'utf8')
const documentAccessMigration = readFileSync('supabase/migrations/20260826000100_employee_document_secure_preview.sql', 'utf8')
const lineLinkMigration = readFileSync('supabase/migrations/20260826180000_employee_admin_line_account_link.sql', 'utf8')
const multipleLineMigration = readFileSync('supabase/migrations/20260826190000_employee_multiple_line_accounts.sql', 'utf8')
const phoneUpdateMigration = readFileSync('supabase/migrations/20260826200000_employee_phone_admin_update.sql', 'utf8')
const secureBankMigration = readFileSync('supabase/migrations/20260826203000_employee_bank_account_secure_store.sql', 'utf8')
const uiActionStandard = readFileSync('docs/UI_ACTION_STANDARD.md', 'utf8')
const telegram = readFileSync('supabase/functions/telegram-admin/index.ts', 'utf8')
const reviewer = readFileSync('supabase/functions/review-employee-intake/index.ts', 'utf8')
const gateway = readFileSync('src/services/documentFlowGateway.ts', 'utf8')
const intakeRoom = readFileSync('src/pages/IntakeRoom.tsx', 'utf8')
const employeePage = readFileSync('src/pages/Employee/index.tsx', 'utf8')
const createEmployee = readFileSync('supabase/functions/create-employee/index.ts', 'utf8')

assert.match(migration, /create_employee_preboarding_from_intake/)
assert.match(migration, /employment_type in \('unknown','daily','monthly','temporary','contractor'\)/)
assert.match(migration, /employee_intake_candidate_name_required/)
assert.match(migration, /employee_intake_document_required/)
assert.match(migration, /employee_status,created_by[\s\S]*'preboarding'/)
assert.match(migration, /sync_employee_intake_person_documents/)
assert.match(migration, /employee_preboarding_created/)
assert.match(migration, /cardinality\(missing_fields\)>0 then 'information_required'/)
assert.match(migration, /if intake\.status<>'pending_review' or cardinality\(intake\.missing_fields\)>0/)
assert.match(migration, /status='approved'/)
assert.match(migration, /revoke all on function public\.create_employee_preboarding_from_intake[\s\S]*grant execute[\s\S]*to service_role/)

assert.match(telegram, /employee_intake:preboard:/)
assert.match(telegram, /create_employee_preboarding_from_intake/)
assert.match(telegram, /สร้างประวัติเบื้องต้น/)
assert.match(reviewer, /action\?: 'create_preboarding'/)
assert.match(reviewer, /linked_document_count/)
assert.match(gateway, /employeeIntakePreview[\s\S]*order\('created_at'\)/)
assert.doesNotMatch(gateway, /employeeIntakePreview[\s\S]{0,300}limit\(1\)/)
assert.match(intakeRoom, /result\.data\.map\(async \(file, index\)/)
assert.match(intakeRoom, /actionMenuRow\.source === 'employee_intake' \|\| actionMenuRow\.review_case_id/)
assert.match(intakeRoom, /ยังไม่เปิด Login\/ลงเวลา\/ค่าแรง/)
assert.match(updateMigration, /update_employee_preboarding_from_intake/)
assert.match(updateMigration, /remaining_fields text\[\]/)
assert.match(updateMigration, /employee_preboarding_updated/)
assert.match(updateMigration, /revoke all on function public\.update_employee_preboarding_from_intake[\s\S]*to service_role/)
assert.match(updateMigration, /cardinality\(next_missing\)=0 then 'pending_review'/)
assert.match(reviewer, /action\?: 'create_preboarding' \| 'update_preboarding'/)
assert.match(employeePage, /เพิ่ม \/ อัปเดตข้อมูล/)
assert.match(employeePage, /action: 'update_preboarding'/)
assert.match(employeePage, /employee_intakes'\)\.select\('id,status,missing_fields'/)
assert.match(employeePage, /employee_people'\)\.select\('id,profile_id,phone'/)
assert.match(employeePage, /พนักงานเตรียมเริ่มงาน/)
assert.match(employeePage, /employee_status','preboarding'\)\.is\('profile_id', null\)/)
assert.match(employeePage, /ขาด: \$\{label\}/)
assert.match(employeePage, /สร้างบัญชี \/ ตั้งค่าสิทธิ์/)
assert.match(employeePage, /sourceEmployeePersonId: preboardingAccountPerson\?\.id/)
assert.match(createEmployee, /employee_preboarding_account_linked/)
assert.match(createEmployee, /ผูกบัญชีกับทะเบียนพนักงานเดิม/)
assert.match(employeePage, /employeeDocumentsByProfile/)
assert.match(employeePage, /เอกสารประจำตัวและเอกสารย้อนหลัง/)
assert.match(employeePage, /บันทึกและยืนยันข้อมูลครบ/)
assert.match(employeePage, /มอบหมายไซต์งาน/)
assert.match(employeePage, /assign_employee_site/)
assert.match(employeePage, /site_assignment_already_active|พนักงานถูกมอบหมายเข้าไซต์นี้อยู่แล้ว/)
assert.match(employeePage, /จัดการประวัติ ย้าย หรือสิ้นสุดไซต์/)
assert.match(employeePage, /drawerAvailableSiteOptions/)
assert.match(employeePage, /มอบหมายครบทุกไซต์ที่เปิดใช้งานแล้ว/)
assert.match(employeePage, /setDrawerSiteId\(''\)/)
assert.match(siteAssignmentMigration, /employee_not_in_company/)
assert.match(siteAssignmentMigration, /site_not_in_company/)
assert.match(siteAssignmentMigration, /policy_not_in_company/)
assert.match(siteAssignmentMigration, /site_assignment_already_active/)
assert.match(siteAssignmentMigration, /employee_site_assignment_events/)
assert.match(siteAssignmentMigration, /'created','มอบหมายไซต์งานให้พนักงาน'/)
assert.match(siteAssignmentMigration, /grant execute[\s\S]*to authenticated/)
assert.match(documentAccessMigration, /request_employee_document_access/)
assert.match(documentAccessMigration, /public\.current_company_id\(\)/)
assert.match(documentAccessMigration, /public\.is_platform_admin\(\) or public\.is_company_manager/)
assert.match(documentAccessMigration, /employee_document_(preview|download)_requested/)
assert.match(documentAccessMigration, /insert into public\.employee_workforce_audit_logs/)
assert.match(documentAccessMigration, /revoke all[\s\S]*grant execute[\s\S]*to authenticated/)
assert.match(employeePage, /request_employee_document_access/)
assert.match(employeePage, /createSignedUrl\(access\.storage_path, 600/)
assert.match(employeePage, /ค้นหา \/ แนบเอกสารเพิ่มจาก Intake/)
assert.match(employeePage, /กดดู/)
assert.match(employeePage, /กำลังตรวจสิทธิ์และเปิดเอกสาร/)
assert.match(employeePage, /ภาพรวม\$\{allMissing\.length/)
assert.match(employeePage, /การจ้างงาน\$\{employmentMissing\.length/)
assert.match(employeePage, /บัญชี\/ติดต่อ\$\{contactMissing\.length/)
assert.match(employeePage, /เอกสาร\$\{documentMissing\.length/)
assert.match(employeePage, /employee_line_accounts/)
assert.match(employeePage, /line_senders\(display_name\)/)
assert.match(employeePage, /master_bank_accounts/)
assert.match(employeePage, /ข้อมูลจากเอกสาร\/LINE จะเป็น Candidate ก่อน/)
assert.match(employeePage, /ตรวจบัญชีจากหลักฐาน/)
assert.match(employeePage, /ตรวจประวัติ LINE \/ Candidate ทั้งหมด/)
assert.match(employeePage, /ผูกบัญชี LINE/)
assert.match(employeePage, /admin_add_employee_line_account/)
assert.match(employeePage, /admin_unlink_employee_line_identity/)
assert.match(employeePage, /เพิ่ม LINE อีกบัญชี/)
assert.match(employeePage, /บัญชีหลัก/)
assert.match(employeePage, /บัญชีรอง/)
assert.match(employeePage, /line_senders'\)\.select\('line_user_id,display_name,picture_url,profile_id,updated_at'/)
assert.match(lineLinkMigration, /public\.is_company_manager\(target_company_id\)/)
assert.match(lineLinkMigration, /LINE นี้ผูกกับพนักงานคนอื่นอยู่แล้ว/)
assert.match(lineLinkMigration, /on conflict \(company_id, channel, profile_id\) do update/)
assert.match(lineLinkMigration, /employee_workforce_audit_logs/)
assert.match(lineLinkMigration, /'employee_line_account'/)
assert.match(lineLinkMigration, /set search_path = ''/)
assert.match(lineLinkMigration, /revoke all on function public\.admin_link_employee_line_account/)
assert.match(lineLinkMigration, /admin_link_employee_line_account\(uuid,text,boolean,text\) from anon/)
assert.match(lineLinkMigration, /admin_unlink_employee_line_account\(uuid,text\) from anon/)
assert.match(multipleLineMigration, /drop constraint if exists employee_line_accounts_company_profile_key/)
assert.match(multipleLineMigration, /employee_line_accounts_one_primary_idx/)
assert.match(multipleLineMigration, /admin_add_employee_line_account/)
assert.match(multipleLineMigration, /admin_unlink_employee_line_identity/)
assert.match(multipleLineMigration, /promoted_account_id/)
assert.match(multipleLineMigration, /claim_line_account/)
assert.match(multipleLineMigration, /from anon/)
assert.match(phoneUpdateMigration, /admin_update_employee_phone/)
assert.match(phoneUpdateMigration, /public\.current_company_id\(\)/)
assert.match(phoneUpdateMigration, /public\.is_company_manager\(target_company_id\)/)
assert.match(phoneUpdateMigration, /employee_workforce_audit_logs/)
assert.match(phoneUpdateMigration, /person\.phone is not distinct from normalized_phone/)
assert.match(phoneUpdateMigration, /revoke all on function public\.admin_update_employee_phone\(uuid,text,text\) from anon/)
assert.match(phoneUpdateMigration, /grant execute on function public\.admin_update_employee_phone\(uuid,text,text\) to authenticated/)
assert.match(employeePage, /admin_update_employee_phone/)
assert.match(employeePage, /aria-label=\{contact\?\.phone \? 'แก้ไขเบอร์โทร' : 'เพิ่มเบอร์โทร'\}/)
assert.match(employeePage, /startIcon=\{<AddOutlinedIcon \/>\}[\s\S]*เพิ่ม LINE อีกบัญชี/)
assert.match(uiActionStandard, /^```mermaid/)
assert.match(uiActionStandard, /Input[\s\S]*Output[\s\S]*State[\s\S]*Roles[\s\S]*Integration[\s\S]*Failure\/Retry[\s\S]*Audit[\s\S]*Owner/)
assert.match(secureBankMigration, /private\.employee_bank_account_secrets/)
assert.match(secureBankMigration, /employee_bank_account_encryption_key/)
assert.match(secureBankMigration, /extensions\.pgp_sym_encrypt/)
assert.match(secureBankMigration, /extensions\.pgp_sym_decrypt/)
assert.match(secureBankMigration, /extensions\.hmac/)
assert.match(secureBankMigration, /company_role in \('company_admin', 'executive', 'accounting_hr'\)/)
assert.match(secureBankMigration, /secure_bank_account_(added|updated)/)
assert.match(secureBankMigration, /full_bank_account_revealed/)
assert.match(secureBankMigration, /account_row\.account_fingerprint = fingerprint[\s\S]*return jsonb_build_object\('status', 'unchanged'/)
assert.match(secureBankMigration, /revoke all on function public\.reveal_employee_bank_account_number\(uuid,text\) from public, anon/)
assert.match(secureBankMigration, /'full_bank_account_revealed'[\s\S]*jsonb_build_object\('bank_name',[\s\S]*'account_last4',[\s\S]*'source', 'employee_drawer'\)/)
assert.match(employeePage, /secure_number_available,is_primary/)
assert.match(employeePage, /มีเพียงเลขท้าย · ต้องเติมเลขเต็ม/)
assert.match(employeePage, /พร้อมใช้จ่าย/)
assert.match(employeePage, /admin_upsert_employee_bank_account/)
assert.match(employeePage, /reveal_employee_bank_account_number/)
assert.match(employeePage, /ซ่อนอัตโนมัติภายใน 60 วินาที/)
assert.match(employeePage, /ตรวจบัญชีจากหลักฐาน/)

console.log('employee preboarding draft checks passed')
