import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'

const migration=readFileSync('supabase/migrations/202608110030_employee_multichannel_intake.sql','utf8')
const approvedExitMigration=readFileSync('supabase/migrations/20260822005245_employee_intake_approved_exit_to_onboarding.sql','utf8')
const telegram=readFileSync('supabase/functions/telegram-admin/index.ts','utf8')

assert.match(migration,/create table if not exists public\.employee_intakes/)
assert.match(migration,/company_id uuid not null references public\.companies/)
assert.match(migration,/enable row level security/)
assert.match(migration,/public\.is_platform_admin\(\) or public\.is_company_manager\(company_id\)/)
assert.match(migration,/employee-intake-documents','employee-intake-documents',false/)
assert.match(migration,/Never store a full national ID/)

assert.match(telegram,/employee_intake:new:/)
assert.match(telegram,/พนักงานใหม่/)
assert.match(telegram,/receiveEmployeeIntakePhoto/)
assert.match(telegram,/analyzeEmployeeIntake/)
assert.match(telegram,/information_required/)
assert.match(telegram,/pending_review/)
assert.match(telegram,/Never return a full national ID/)
assert.match(telegram,/delete safeFields\.national_id/)
assert.match(telegram,/candidate_name','phone','employment_type','position','start_date/)
assert.match(telegram,/import_line_employee_intake/)
assert.match(telegram,/preview_employee_intake/)
assert.match(telegram,/ข้อมูลสำคัญก่อนตัดสินใจ/)
assert.match(telegram,/replay_employee_intake_reply/)
assert.match(telegram,/parseEmployeeIntakeAdditions/)
assert.match(telegram,/looksLikeCandidateName/)
assert.match(telegram,/\\p\{L\}\\p\{M\}/)
assert.match(telegram,/Date\.now\(\)-24\*60\*60_000/)
assert.match(telegram,/fallback\?\.length===1/)
assert.match(telegram,/ลูกจ้าง\)\?รายวัน/)
assert.match(telegram,/พนักงานเงินเดือน/)
assert.match(telegram,/Asia\/Bangkok/)
assert.match(telegram,/0\\d\{9\}/)
assert.match(telegram,/ชื่อ–นามสกุล:/)
assert.match(telegram,/อ่านชื่อ–นามสกุลไม่สำเร็จ/)
assert.match(telegram,/send_employee_intake_summary/)
assert.match(telegram,/candidate_name: ชื่อ นามสกุล/)
assert.match(telegram,/employee_document_ai_not_configured/)
assert.match(telegram,/gemini-3\.6-flash','gemini-3\.5-flash','gemini-2\.0-flash/)
assert.match(telegram,/\[404,429,503\]\.includes\(response\.status\)/)
assert.match(telegram,/อ่านข้อมูลจากเอกสารไม่ได้/)
assert.match(telegram,/จึงไม่สร้างร่างพนักงานและไม่เปิดให้อนุมัติ/)
assert.match(telegram,/broadcastEmployeeIntake/)
assert.match(telegram,/duplicate_skipped:true/)
assert.match(telegram,/_telegram_delivery/)
assert.match(telegram,/_telegram_input/)
assert.match(telegram,/employee_intake_duplicate_ignored/)
assert.match(telegram,/for\(const key of \['candidate_name','phone','employment_type','position','start_date'\]\)/)
assert.match(telegram,/nameVariants\.size>1&&!merged\.candidate_name/)
assert.match(telegram,/previousInput=existing\._telegram_input/)
assert.match(telegram,/employee_intake_already_ready/)
assert.match(telegram,/review_ready/)
assert.match(telegram,/fields_summary/)
assert.match(telegram,/repair_employee_intake_encoding/)
assert.match(telegram,/repairEmployeeIntakeEncoding/)
assert.match(telegram,/authorization'\)!==`Bearer \$\{serviceKey\}`/)
assert.match(telegram,/source_channel:'line'/)
assert.doesNotMatch(migration,/national_id\s+(text|varchar|character)/i)
assert.match(approvedExitMigration,/e\.status not in \('approved','cancelled'\)/)
assert.match(approvedExitMigration,/employee_people\.employee_status = preboarding/)
assert.match(approvedExitMigration,/update public\.employee_intakes intake/)

console.log('employee multichannel intake checks passed')
