import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const migration = readFileSync('supabase/migrations/20260825203000_employee_intake_preboarding_draft.sql', 'utf8')
const updateMigration = readFileSync('supabase/migrations/20260825212911_employee_intake_preboarding_update.sql', 'utf8')
const siteAssignmentMigration = readFileSync('supabase/migrations/20260825231500_employee_drawer_site_assignment_audit.sql', 'utf8')
const telegram = readFileSync('supabase/functions/telegram-admin/index.ts', 'utf8')
const reviewer = readFileSync('supabase/functions/review-employee-intake/index.ts', 'utf8')
const gateway = readFileSync('src/services/documentFlowGateway.ts', 'utf8')
const intakeRoom = readFileSync('src/pages/IntakeRoom.tsx', 'utf8')
const employeePage = readFileSync('src/pages/Employee/index.tsx', 'utf8')
const createEmployee = readFileSync('supabase/functions/create-employee/index.ts', 'utf8')

assert.match(migration, /create_employee_preboarding_from_intake/)
assert.match(migration, /employment_type in \('unknown','daily','monthly','temporary','contractor'\)/)
assert.match(migration, /employee_intake_candidate_name_required/)
assert.match(migration, /employee_intake_document_required/)
assert.match(migration, /employee_status,created_by[\s\S]*'preboarding'/)
assert.match(migration, /sync_employee_intake_person_documents/)
assert.match(migration, /employee_preboarding_created/)
assert.match(migration, /cardinality\(missing_fields\)>0 then 'information_required'/)
assert.match(migration, /if intake\.status<>'pending_review' or cardinality\(intake\.missing_fields\)>0/)
assert.match(migration, /status='approved'/)
assert.match(migration, /revoke all on function public\.create_employee_preboarding_from_intake[\s\S]*grant execute[\s\S]*to service_role/)

assert.match(telegram, /employee_intake:preboard:/)
assert.match(telegram, /create_employee_preboarding_from_intake/)
assert.match(telegram, /สร้างประวัติเบื้องต้น/)
assert.match(reviewer, /action\?: 'create_preboarding'/)
assert.match(reviewer, /linked_document_count/)
assert.match(gateway, /employeeIntakePreview[\s\S]*order\('created_at'\)/)
assert.doesNotMatch(gateway, /employeeIntakePreview[\s\S]{0,300}limit\(1\)/)
assert.match(intakeRoom, /result\.data\.map\(async \(file, index\)/)
assert.match(intakeRoom, /actionMenuRow\.source === 'employee_intake' \|\| actionMenuRow\.review_case_id/)
assert.match(intakeRoom, /ยังไม่เปิด Login\/ลงเวลา\/ค่าแรง/)
assert.match(updateMigration, /update_employee_preboarding_from_intake/)
assert.match(updateMigration, /remaining_fields text\[\]/)
assert.match(updateMigration, /employee_preboarding_updated/)
assert.match(updateMigration, /revoke all on function public\.update_employee_preboarding_from_intake[\s\S]*to service_role/)
assert.match(updateMigration, /cardinality\(next_missing\)=0 then 'pending_review'/)
assert.match(reviewer, /action\?: 'create_preboarding' \| 'update_preboarding'/)
assert.match(employeePage, /เพิ่ม \/ อัปเดตข้อมูล/)
assert.match(employeePage, /action: 'update_preboarding'/)
assert.match(employeePage, /employee_intakes'\)\.select\('id,status,missing_fields'/)
assert.match(employeePage, /employee_people'\)\.select\('id,profile_id'/)
assert.match(employeePage, /พนักงานเตรียมเริ่มงาน/)
assert.match(employeePage, /employee_status','preboarding'\)\.is\('profile_id', null\)/)
assert.match(employeePage, /ขาด: \$\{label\}/)
assert.match(employeePage, /สร้างบัญชี \/ ตั้งค่าสิทธิ์/)
assert.match(employeePage, /sourceEmployeePersonId: preboardingAccountPerson\?\.id/)
assert.match(createEmployee, /employee_preboarding_account_linked/)
assert.match(createEmployee, /ผูกบัญชีกับทะเบียนพนักงานเดิม/)
assert.match(employeePage, /employeeDocumentsByProfile/)
assert.match(employeePage, /เอกสารประจำตัวและเอกสารย้อนหลัง/)
assert.match(employeePage, /บันทึกและยืนยันข้อมูลครบ/)
assert.match(employeePage, /มอบหมายไซต์งาน/)
assert.match(employeePage, /assign_employee_site/)
assert.match(employeePage, /site_assignment_already_active|พนักงานถูกมอบหมายเข้าไซต์นี้อยู่แล้ว/)
assert.match(employeePage, /จัดการประวัติ ย้าย หรือสิ้นสุดไซต์/)
assert.match(siteAssignmentMigration, /employee_not_in_company/)
assert.match(siteAssignmentMigration, /site_not_in_company/)
assert.match(siteAssignmentMigration, /policy_not_in_company/)
assert.match(siteAssignmentMigration, /site_assignment_already_active/)
assert.match(siteAssignmentMigration, /employee_site_assignment_events/)
assert.match(siteAssignmentMigration, /'created','มอบหมายไซต์งานให้พนักงาน'/)
assert.match(siteAssignmentMigration, /grant execute[\s\S]*to authenticated/)

console.log('employee preboarding draft checks passed')
