import assert from 'node:assert/strict'
import fs from 'node:fs'

const service = fs.readFileSync('src/services/notificationCenter.ts', 'utf8')
const page = fs.readFileSync('src/pages/Notifications/NotificationCenterPage.tsx', 'utf8')
const bell = fs.readFileSync('src/components/NotificationBell.tsx', 'utf8')
const router = fs.readFileSync('src/router/index.tsx', 'utf8')
assert.match(service, /communication_event_feed/)
assert.match(service, /notification_read_states/)
assert.match(service, /fixture:advance/)
assert.match(service, /fixture:slip/)
assert.match(service, /fixture:attendance/)
assert.match(service, /fixture:system/)
assert.match(service, /source: 'local_fixture'/)
assert.match(page, /ยังไม่อ่าน/)
assert.match(page, /งานที่ต้องทำ/)
assert.match(page, /แจ้งเตือนระบบ/)
assert.match(page, /เปิดงาน/)
assert.match(page, /SLA:/)
assert.match(page, /Owner:/)
assert.match(page, /LOCAL FIXTURE/)
assert.match(page, /moduleFilter/)
assert.match(page, /setModuleFilter/)
assert.match(page, /notification_read_states/)
assert.match(bell, /unreadCount/)
assert.match(bell, /actionableCount/)
assert.match(bell, /การแจ้งเตือน/)
assert.match(router, /NotificationCenterPage/)
console.log('notification center contract tests passed: source feed, fixture priorities, unread badge, filters, deep-links and read audit')
