import assert from 'node:assert/strict'
import fs from 'node:fs'

const service = fs.readFileSync('src/services/notificationCenter.ts', 'utf8')
const page = fs.readFileSync('src/pages/Notifications/NotificationCenterPage.tsx', 'utf8')
const bell = fs.readFileSync('src/components/NotificationBell.tsx', 'utf8')
const router = fs.readFileSync('src/router/index.tsx', 'utf8')
assert.match(service, /rpc\('get_communication_event_feed'/)
assert.doesNotMatch(service, /from\('communication_event_feed'\)/)
assert.match(service, /notification_read_states/)
assert.match(service, /actionableEventTypes/)
assert.match(service, /'incident', 'repeat', 'approval_required', 'review_required'/)
assert.match(service, /eventType === 'incident'/)
assert.match(service, /actionableCount: items\.filter\(\(item\) => item\.kind === 'actionable'\)\.length/)
assert.doesNotMatch(service, /item\.kind === 'actionable' && !item\.read/)
assert.match(service, /fixture:advance/)
assert.match(service, /fixture:slip/)
assert.match(service, /fixture:attendance/)
assert.match(service, /fixture:system/)
assert.match(service, /source: 'local_fixture'/)
assert.match(page, /ยังไม่อ่าน/)
assert.match(page, /งานที่ต้องทำ/)
assert.match(page, /แจ้งเตือนระบบ/)
assert.match(page, /เปิดงาน/)
assert.match(page, /SLA:/)
assert.match(page, /Owner:/)
assert.match(page, /Source:/)
assert.match(page, /Ref:/)
assert.match(page, /LOCAL FIXTURE/)
assert.match(page, /moduleFilter/)
assert.match(page, /setModuleFilter/)
assert.match(page, /params\.get\('module'\)/)
assert.match(page, /canManageCompany/)
assert.match(page, /notification_read_states/)
assert.doesNotMatch(page, /actionableCount: item\.kind/)
assert.match(bell, /unreadCount/)
assert.match(bell, /actionableCount/)
assert.match(bell, /การแจ้งเตือน/)
assert.match(bell, /canManageCompany/)
assert.match(router, /NotificationCenterPage/)
console.log('notification center contract tests passed: source feed, fixture priorities, unread badge, filters, deep-links and read audit')
