import { readFileSync } from 'node:fs'
import assert from 'node:assert/strict'

const page=readFileSync('src/pages/PlatformControlCenter/index.tsx','utf8')
const route=readFileSync('src/router/index.tsx','utf8')
const role=readFileSync('src/router/RoleRoute.tsx','utf8')
const nav=readFileSync('src/utils/navigation.ts','utf8')
const baseMigration=readFileSync('supabase/migrations/202608150021_platform_control_center.sql','utf8')
const completionMigration=readFileSync('supabase/migrations/202608160012_platform_control_center_completion.sql','utf8')

assert.match(route,/platform-control-center.*platformOnly/)
assert.match(role,/platform_role==='admin'/)
assert.doesNotMatch(nav,/platform-control-center/)
const topBar=readFileSync('src/layouts/TopBar.tsx','utf8')
assert.match(topBar,/__platform__/)
assert.match(topBar,/ศูนย์จัดการระบบกลาง/)
assert.match(topBar,/platform_role === 'admin'/)
assert.doesNotMatch(page,/currentCompany|current_company_id/)
assert.match(page,/get_platform_control_center_snapshot/)
assert.match(page,/Service Health Map/)
assert.match(page,/บริษัท → โครงการ → ไซต์ → พนักงาน/)
assert.match(page,/ยืนยันเลือกบริษัท/)
assert.match(page,/type WindowKey='24h'\|'7d'\|'30d'/)
assert.match(page,/fingerprint/)
assert.match(page,/user_report_count/)
assert.doesNotMatch(page,/Drill-down ใช้ Snapshot/)
assert.match(baseMigration,/public\.is_platform_admin\(\)/)
assert.match(completionMigration,/target_window not in \('24h','7d','30d'\)/)
assert.match(completionMigration,/last_checked_at>=since_at/)
assert.match(completionMigration,/group by module/)
assert.match(completionMigration,/'children'/)
assert.match(completionMigration,/user_report_count/)
assert.match(completionMigration,/where work_key='PLATFORM-CONTROL-CENTER-001'/)
assert.doesNotMatch(completionMigration,/insert into public\.system_work_items/i)
assert.match(completionMigration,/revoke all .* from public,anon/)
assert.doesNotMatch(completionMigration,/jsonb_build_object\([^)]*'(secret|token)'/i)
console.log('platform control center functional contract: passed')
