import { readFileSync } from 'node:fs'
import assert from 'node:assert/strict'
const sql=readFileSync(new URL('../supabase/migrations/202608110035_realtime_payroll_forecast.sql',import.meta.url),'utf8')
const fixSql=readFileSync(new URL('../supabase/migrations/202608110036_fix_realtime_payroll_forecast_rpc.sql',import.meta.url),'utf8')
const ui=readFileSync(new URL('../src/pages/Reports/RealtimePayrollForecast.tsx',import.meta.url),'utf8')
const reports=readFileSync(new URL('../src/pages/Reports/index.tsx',import.meta.url),'utf8')
assert.match(sql,/employee_compensation_rates/)
assert.match(sql,/workforce_daily_plans/)
assert.match(sql,/get_realtime_payroll_forecast/)
assert.match(sql,/'PAYROLL-FORECAST-001'[\s\S]*'report'/)
assert.match(sql,/company_id=public\.current_company_id\(\)/)
assert.match(sql,/not public\.is_work_manager\(\)/)
assert.match(sql,/Forecast data is separate from approved payroll and payslips/)
assert.doesNotMatch(sql,/update\s+employee_payrolls/i)
assert.match(fixSql,/coalesce\(\(select wrs\.full_day_minutes/)
assert.match(fixSql,/e\.employee_name::text/)
assert.match(fixSql,/coalesce\(a\.normal_minutes,0\)::bigint/)
assert.doesNotMatch(fixSql,/update\s+employee_payrolls/i)
assert.match(ui,/postgres_changes[\s\S]*attendance_sessions/)
assert.match(ui,/ไม่กระทบงวดที่อนุมัติหรือจ่ายแล้ว/)
assert.match(reports,/workedMinutes>=summaryStandardMinutes\?1:workedMinutes>=summaryStandardMinutes\/2\?0\.5:0/)
assert.match(reports,/เงินเดือนเฉลี่ยตามวันทำงานในตาราง สะสมถึงวันปัจจุบัน/)
assert.match(reports,/วันค่าแรง/)
assert.match(reports,/ค่าแรงปกติ/)
assert.match(reports,/สุทธิวันนี้/)
assert.match(reports,/พิมพ์ \/ บันทึก PDF รายบุคคล/)
assert.match(reports,/else if\(date<today\)state='หยุด'/)
assert.match(reports,/ชื่อพนักงาน: \$\{escape\(summaryTarget\.name\)\}/)
assert.match(reports,/<title>รายงานค่าแรง-\$\{escape\(summaryTarget\.name\)\}-\$\{escape\(month\)\}<\/title>/)
assert.match(reports,/const optionalDuration=.*\?duration\(minutes\):'-'/)
assert.match(reports,/getRowSx=\{monthDayRowSx\}/)
assert.match(reports,/วันค่าแรงสุทธิ/)
assert.doesNotMatch(reports,/รวมเวลาสุทธิ/)
assert.doesNotMatch(reports,/class="total"/,'individual PDF must keep the single summary at the top')
console.log('realtime payroll forecast checks passed')
