import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'

const migration=readFileSync('supabase/migrations/202608120003_site_assignment_history_policy_resolution.sql','utf8')
const clock=readFileSync('supabase/functions/attendance-clock/index.ts','utf8')
const employee=readFileSync('src/pages/Employee/index.tsx','utf8')
const tracking=readFileSync('src/pages/TimeTracking/index.tsx','utf8')
const setup=readFileSync('src/pages/WorkforceSetup/index.tsx','utf8')
const lifecycle=readFileSync('supabase/migrations/202608120005_site_assignment_lifecycle.sql','utf8')

assert.match(migration,/primary key\(id\)/)
assert.match(migration,/employee_site_assignment_period_key/)
assert.match(migration,/work_policy_id uuid references public\.work_policies/)
assert.match(migration,/is_primary boolean not null default false/)
assert.match(migration,/assign_employee_site/)
assert.match(migration,/target_starts_on-1/)
assert.match(migration,/assignment_id uuid references public\.employee_site_assignments/)
assert.match(migration,/policy_snapshot jsonb/)
assert.match(migration,/bool_and\(coalesce\(site_assignment\.work_policy_id,employment\.work_policy_id,site\.work_policy_id\) is not null\)/)
assert.match(clock,/assignment\?\.work_policy_id\?\?employment\?\.work_policy_id\?\?site\.work_policy_id/)
assert.match(clock,/policy_snapshot:resolvedPolicy/)
assert.match(employee,/!employee\.has_work_policy/)
assert.match(tracking,/rpc\('assign_employee_site'/)
assert.match(setup,/rpc\('assign_employee_site'/)
assert.match(setup,/การมอบหมายปัจจุบันและประวัติ/)
assert.match(setup,/target_is_primary:employeeAssignment\.isPrimary/)
assert.match(lifecycle,/employee_site_assignment_events/)
assert.match(lifecycle,/assignment_has_attendance_use_end_instead/)
assert.match(lifecycle,/status='void'/)
assert.doesNotMatch(lifecycle,/delete from public\.employee_site_assignments/)
assert.match(setup,/manage_employee_site_assignment/)
assert.match(setup,/prepareEdit/)
assert.match(setup,/เหตุผลที่แก้ไข/)
assert.match(setup,/target_action:'update'/)
assert.match(setup,/handleAssignmentAction/)
assert.match(setup,/AccordionSummary/)
console.log('effective-dated multi-site policy resolution regression passed')
