import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const migration = readFileSync('supabase/migrations/202608150001_system_error_intake_and_user_evidence.sql', 'utf8')
const resolutionMigration = readFileSync('supabase/migrations/202608150002_system_error_resolution_workflow.sql', 'utf8')
const reconciliationMigration = readFileSync('supabase/migrations/202608150004_error_lifecycle_reconciliation.sql', 'utf8')
const imageEvidenceMigration = readFileSync('supabase/migrations/202608150009_line_system_error_evidence.sql', 'utf8')
const historicalEvidenceMigration = readFileSync('supabase/migrations/202608150010_historical_line_error_evidence_and_storage_policy.sql', 'utf8')
const optimizationMigration = readFileSync('supabase/migrations/202608150011_local_image_storage_optimization.sql', 'utf8')
const optimizationFunction = readFileSync('supabase/functions/image-storage-optimizer/index.ts', 'utf8')
const telemetry = readFileSync('src/components/AppTelemetry.tsx', 'utf8')
const client = readFileSync('src/lib/supabase.ts', 'utf8')
const line = readFileSync('supabase/functions/line-webhook/index.ts', 'utf8')
const monitor = readFileSync('supabase/functions/health-monitor/index.ts', 'utf8')
const systemHealth = readFileSync('src/pages/SystemHealth/index.tsx', 'utf8')
const appTelemetry = readFileSync('src/components/AppTelemetry.tsx', 'utf8')
const authReconciliation = readFileSync('supabase/migrations/202608150018_expected_auth_error_reconciliation.sql', 'utf8')
const completionReconciliation = readFileSync('supabase/migrations/202608150020_system_health_runtime_repairs_completion.sql', 'utf8')

assert.match(migration, /create table if not exists public\.system_error_events/)
assert.match(migration, /unique\(company_id,fingerprint\)/)
assert.match(migration, /on conflict\(company_id,fingerprint\) do update set/)
assert.match(migration, /occurrence_count=system_error_events\.occurrence_count\+1/)
assert.match(migration, /event\.correlation_key=normalized_correlation/)
assert.match(migration, /event\.metadata->>'error_code'/)
assert.match(migration, /user_report_count=user_report_count\+case when target_is_user_report then 1 else 0 end/)
assert.match(migration, /public\.is_company_manager\(company_id\)/)
assert.match(migration, /grant execute on function public\.upsert_system_error_event[\s\S]*to service_role/)
assert.match(migration, /where work_key='SYS-004'/)
assert.match(migration, /get_system_error_statistics/)
assert.match(migration, /'system_occurrences'/)
assert.match(migration, /'user_confirmations'/)

assert.match(client, /wisdomai-request-error/)
assert.match(client, /if \(!response\.ok\) \{\s*const body = await response\.clone\(\)\.text\(\)\.catch\(\(\) => ''\)\s*emitRequestError/)
assert.match(telemetry, /registerClientError/)
assert.match(telemetry, /eventType: source === 'request' \? 'request_error' : 'client_error'/)
assert.match(telemetry, /unhandledrejection/)

assert.match(line, /system_error:/)
assert.match(line, /target_source: 'line_user_screenshot'/)
assert.match(line, /target_is_user_report: true/)
assert.match(line, /system_error_evidence_linked/)
assert.match(line, /\? 'system_error'/)
assert.match(imageEvidenceMigration, /'system_error','ผู้ใช้แจ้ง Error ระบบ'/)
assert.match(imageEvidenceMigration, /register_reviewed_system_error_image/)
assert.match(imageEvidenceMigration, /'line_user_screenshot'/)
assert.match(imageEvidenceMigration, /review_row\.source_message_id/)
assert.match(historicalEvidenceMigration, /create table if not exists public\.system_error_evidence/)
assert.match(historicalEvidenceMigration, /proposed_primary_purpose='system_error'/)
assert.match(historicalEvidenceMigration, /error_code_module_time/)
assert.match(historicalEvidenceMigration, /line_image_storage_report/)
assert.match(historicalEvidenceMigration, /retention_class='system_error'/)
assert.match(optimizationMigration, /line_image_optimization_progress/)
assert.match(optimizationMigration, /optimization_status/)
assert.doesNotMatch(optimizationFunction, /magick-wasm/)
assert.match(optimizationFunction, /maxSize:2500,quality:95,thumbnailQuality:85/)
assert.match(optimizationFunction, /maxSize:2000,quality:90,thumbnailQuality:80/)
assert.match(optimizationFunction, /maxSize:1600,quality:80,thumbnailQuality:75/)
assert.match(optimizationFunction, /download\(attachment\.storage_path,\{transform:/)
assert.match(optimizationFunction, /resize:'contain'/)
assert.match(optimizationFunction, /storage_bytes_saved/)
assert.doesNotMatch(optimizationFunction, /GEMINI/)
assert.match(line, /retentionClass === 'temporary'/)
assert.match(line, /system_error_evidence'\)\.upsert/)
assert.match(line, /optimizeIncomingImage/)
assert.match(line, /processing_stage:'image_optimization'/)
assert.match(line, /main\.byteLength\+optimized\.thumbnail\.byteLength<bytes\.byteLength/)
assert.match(monitor, /target_source: 'health_monitor'/)
assert.match(monitor, /target_is_user_report: false/)
assert.match(resolutionMigration, /resolve_system_error_event\(/)
assert.match(resolutionMigration, /public\.is_company_manager\(result\.company_id\)/)
assert.match(resolutionMigration, /resolution_reason text/)
assert.match(resolutionMigration, /reconcile_system_error_work_item/)
assert.match(reconciliationMigration, /reconcile_system_error_events/)
assert.match(reconciliationMigration, /event\.fingerprint=any\(coalesce\(target_healthy_fingerprints/)
assert.match(reconciliationMigration, /event\.first_source like 'web:%'/)
assert.match(reconciliationMigration, /check_row\.status='healthy'/)
assert.match(monitor, /healthyFingerprints=results\.filter\(result=>result\.status==='healthy'\)/)
assert.match(monitor, /admin\.rpc\('reconcile_system_error_events'/)
assert.match(monitor, /latest_error_id/)
assert.match(monitor, /isRepeatedClientSnapshot/)
assert.match(monitor, /not_ready_people:people/)
assert.match(monitor, /ขาด \$\{person\.missing\.join/)
assert.match(systemHealth, /system_error_events[^\n]*resolution_reason,resolved_at/)
assert.match(systemHealth, /system_error_events[^\n]*\.eq\('company_id',companyId\)/)
assert.match(systemHealth, /readableCheckMessage\(userError\(event\),'ไม่มีรายละเอียดเพิ่มเติม'\)/)
assert.match(systemHealth, /readableCheckMessage\(userError\(incident\),'ระบบตรวจพบความผิดปกติ'\)/)
assert.match(systemHealth, /value\.trim\(\)!=='\[object Object\]'/)
assert.match(systemHealth, /status:'open'\|'monitoring'\|'resolved'\|'dismissed'/)
assert.match(systemHealth, /\['ทะเบียน Error',errorRows\.error\]/)
assert.match(systemHealth, /resolve_system_error_event/)
assert.doesNotMatch(systemHealth, /window\.prompt/)
assert.match(systemHealth, /ยืนยันและบันทึก Audit/)
assert.match(appTelemetry, /isExpectedRequestOutcome/)
assert.match(appTelemetry, /\/auth\/v1\/token/)
assert.match(appTelemetry, /status === 400 \|\| status === 401/)
assert.match(authReconciliation, /lower\(affected_module\) like '%\/auth\/v1\/token%'/)
assert.match(authReconciliation, /select public\.reconcile_system_error_work_item\(\)/)
assert.match(systemHealth, /ดูรูปหลักฐาน/)
assert.match(systemHealth, /รายงานพื้นที่รูปจาก LINE/)

assert.match(completionReconciliation, /update public\.system_work_items/)
assert.match(completionReconciliation, /where work_key = 'SYS-004'/)
assert.match(completionReconciliation, /and scope = 'platform'/)
assert.doesNotMatch(completionReconciliation, /insert into public\.system_work_items/)
assert.match(completionReconciliation, /Source verification refreshed 2026-08-16/)
assert.match(completionReconciliation, /No migration or deployment was run during this verification/)

console.log('central system error intake and LINE evidence regression tests passed')
