import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const page = readFileSync(new URL('../src/pages/AccountingDocuments/index.tsx', import.meta.url), 'utf8')
const model = readFileSync(new URL('../src/services/transferSlipMoneyLineage.ts', import.meta.url), 'utf8')
const migration = readFileSync(new URL('../supabase/migrations/20260829003040_transfer_slip_allocation_account_selection.sql', import.meta.url), 'utf8')
const controlFundMigration = readFileSync(new URL('../supabase/migrations/20260829093532_prevent_control_fund_expense_accounts.sql', import.meta.url), 'utf8')

assert.match(page, /2\. เลือกรายการบัญชีค่าใช้จ่าย/)
assert.match(page, /รายการบัญชีจากข้อมูลกลาง/)
assert.match(page, /จำเป็นก่อนยืนยัน/)
assert.match(page, /ไม่ลงบัญชีค่าใช้จ่ายในขั้นนี้/)
assert.match(page, /ค่าใช้จ่ายจะบันทึกภายหลังเมื่อมีสลิปหรือหลักฐานการใช้เงินจริง/)
assert.match(page, /persistedLineageResult/)
assert.match(page, /บันทึกแล้ว · รอจับคู่ผู้ถือเงิน ไม่ต้องบันทึกซ้ำ/)
assert.match(page, /slipLineageFinalized/)
assert.match(page, /slipLineagePendingMatch/)
assert.match(page, /ส่งต่อแล้ว · ข้อมูลเดิมถูกเก็บใน Audit/)
assert.match(page, /บันทึกยืนยันแล้ว · รอจับคู่ผู้ถือเงิน/)
assert.match(page, /รายการนี้ยืนยันและส่งต่อแล้ว · ไม่ต้องบันทึกซ้ำ/)
assert.match(page, /แก้ไขข้อมูลจัดสรร/)
assert.match(page, /ยืนยันการแก้ไขและส่งต่อ/)
assert.match(page, /accounting_cost_categories/)
assert.match(page, /cost_category_id/)
assert.match(page, /canonical_accounting_cost_category/)
assert.match(model, /moneyPurposeNeedsExpenseAccount/)
assert.match(model, /บัญชีค่าใช้จ่ายรายการที่/)
assert.match(migration, /add column if not exists cost_category_id/)
assert.match(migration, /money_allocation_account_required/)
assert.match(migration, /category\.company_id is null or category\.company_id = new\.company_id/)
assert.doesNotMatch(migration, /create table .*account/i)
assert.match(controlFundMigration, /control_fund_is_not_expense/)
assert.match(controlFundMigration, /control_fund_expense_account_cleared/)
assert.match(controlFundMigration, /new\.purpose_type not in/)
assert.match(controlFundMigration, /new\.cost_category_id := null/)
assert.match(controlFundMigration, /old_account_code/)
assert.doesNotMatch(controlFundMigration, /update public\.(financial_transactions|document_flow_raw_messages)/i)

console.log('transfer slip account selection contract: PASS')
