import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const source=readFileSync('src/pages/WorkCommandCenter/index.tsx','utf8')
assert.match(source,/งานที่ต้องลงมือ/)
assert.match(source,/รอตรวจ\/อนุมัติ/)
assert.match(source,/system_work_item_events/)
assert.match(source,/Timeline และ Audit/)
assert.match(source,/target_company_id:\s*currentCompany\.company_id/)
assert.match(source,/ขึ้นระบบและตรวจผ่าน/)
assert.ok(source.indexOf('normalized.includes("not_deploy")') < source.indexOf('normalized.includes("deployed")'), 'not_deployed must be classified before deployed')
assert.match(source,/lease_expires_at/)
assert.match(source,/worker_id/)
assert.match(source,/hasActiveWorkerClaim/)
assert.match(source,/workerClaimLabel/)
assert.match(source,/view\s*===\s*["']doing["'][\s\S]*?rows\.filter\(\(row\)\s*=>\s*hasActiveWorkerClaim\(row, claimNow\)\)/)
assert.match(source,/setSelected\(\(current\)[\s\S]*?next\.find/)
assert.match(source,/setCreateOpen\(true\)/)
assert.match(source,/view\s*===\s*["']active["'][\s\S]*?rows\.filter\(\(row\)\s*=>\s*row\.status\s*!==\s*["']done["']\)/)
assert.match(source,/decide_system_work_item_approval/)
assert.match(source,/target_decision:\s*approved \? ['"]approve['"] : ['"]reject['"]/)
assert.match(source,/target_channel:\s*['"]web['"]/)
assert.match(source,/อนุมัติ.*บันทึก Audit/)
assert.match(source,/production_status,owner,current_step,worker_id,heartbeat_at,lease_expires_at,created_at,updated_at/)
assert.doesNotMatch(source,/select\([\s\S]*detail,production_status[\s\S]*evidence,current_step/)
assert.match(source,/select\("detail,evidence"\)/)
assert.match(source,/const \[detailResult, eventsResult\] = await Promise\.all/)
assert.doesNotMatch(source,/อนุมัติและปิดงาน/)
assert.match(source,/selected\.status\s*===\s*["']review["']/)
assert.match(source,/result_status\s*===\s*["']already_decided["']/)
assert.doesNotMatch(source,/\.from\(["']system_work_items["']\)\s*\.update/)
console.log('Work Command Center action UX checks passed')
