import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const source=readFileSync('src/pages/WorkCommandCenter/index.tsx','utf8')
assert.match(source,/งานที่ต้องลงมือ/)
assert.match(source,/รอตรวจ\/อนุมัติ/)
assert.match(source,/system_work_item_events/)
assert.match(source,/Timeline และ Audit/)
assert.match(source,/target_company_id:\s*currentCompany\.company_id/)
assert.match(source,/ขึ้นระบบและตรวจผ่าน/)
assert.ok(source.indexOf('normalized.includes("not_deploy")') < source.indexOf('normalized.includes("deployed")'), 'not_deployed must be classified before deployed')
assert.match(source,/lease_expires_at/)
assert.match(source,/Worker ขาดการติดต่อ/)
assert.match(source,/setSelected\(\(current\)[\s\S]*?next\.find/)
assert.match(source,/setCreateOpen\(true\)/)
assert.match(source,/view\s*===\s*["']active["'][\s\S]*?rows\.filter\(\(row\)\s*=>\s*row\.status\s*!==\s*["']done["']\)/)
assert.match(source,/status:\s*['"]ready['"] as WorkStatus/)
assert.match(source,/อนุมัติให้ดำเนินการ/)
assert.doesNotMatch(source,/อนุมัติและปิดงาน/)
assert.match(source,/selected\.status\s*===\s*["']review["']/)
assert.match(source,/status:\s*["']ready["'] as WorkStatus/)
assert.match(source,/production_status:\s*["']approved_for_execution["']/)
assert.match(source,/\.eq\(["']status["'],\s*["']review["']\)/)
assert.match(source,/status:\s*["']blocked["'] as WorkStatus/)
console.log('Work Command Center action UX checks passed')
