-- DOC-INGEST-003: tenant-scoped original evidence recovery and metadata guardrails.
-- Additive only: no object move/delete and no raw/OCR overwrite.

create or replace function public.is_document_operations(target_company_id uuid default public.current_company_id())
returns boolean
language sql stable security definer set search_path = public, pg_temp
as $$
  select public.is_platform_admin()
    or exists (
      select 1
      from public.company_members member
      where member.company_id = target_company_id
        and member.profile_id = auth.uid()
        and member.active
        and (member.ends_on is null or member.ends_on >= current_date)
        and member.company_role in ('company_admin','executive','manager','accounting_hr')
    );
$$;
revoke all on function public.is_document_operations(uuid) from public, anon;
grant execute on function public.is_document_operations(uuid) to authenticated;

create table if not exists public.document_original_recovery_grants (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  attachment_id uuid not null references public.line_attachments(id) on delete restrict,
  requested_by uuid not null references public.profiles(id) on delete restrict,
  approved_by uuid references public.profiles(id) on delete restrict,
  status text not null default 'pending' check (status in ('pending','approved','used','expired','rejected','revoked')),
  reason text not null check (length(btrim(reason)) between 5 and 500),
  storage_bucket text not null,
  storage_path text not null,
  content_sha256 text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  approved_at timestamptz,
  used_at timestamptz,
  check (expires_at <= coalesce(approved_at, created_at) + interval '15 minutes'),
  unique (company_id, attachment_id, requested_by, created_at)
);
create index if not exists document_original_recovery_grants_queue_idx
  on public.document_original_recovery_grants(company_id, status, expires_at);
create unique index if not exists document_original_recovery_one_open_per_attachment_idx
  on public.document_original_recovery_grants(company_id, attachment_id)
  where status in ('pending','approved');
alter table public.document_original_recovery_grants enable row level security;
drop policy if exists "Document operations read recovery grants" on public.document_original_recovery_grants;
create policy "Document operations read recovery grants"
  on public.document_original_recovery_grants for select to authenticated
  using (company_id = public.current_company_id() and public.is_document_operations(company_id));
revoke insert, update, delete on public.document_original_recovery_grants from anon, authenticated;

create table if not exists public.document_original_recovery_audit (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  grant_id uuid not null references public.document_original_recovery_grants(id) on delete restrict,
  event_key text not null,
  actor_id uuid references public.profiles(id) on delete set null,
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (grant_id, event_key)
);
create index if not exists document_original_recovery_audit_company_idx
  on public.document_original_recovery_audit(company_id, created_at desc);
alter table public.document_original_recovery_audit enable row level security;
create policy "Document operations read recovery audit"
  on public.document_original_recovery_audit for select to authenticated
  using (company_id = public.current_company_id() and public.is_document_operations(company_id));
revoke insert, update, delete on public.document_original_recovery_audit from anon, authenticated;

create or replace function public.request_document_original_recovery(target_attachment_id uuid, target_reason text)
returns public.document_original_recovery_grants
language plpgsql security definer set search_path = public, pg_temp
as $$
declare company uuid := public.current_company_id(); attachment public.line_attachments; result public.document_original_recovery_grants;
begin
  if company is null or not public.is_document_operations(company) then raise exception 'document_operations_permission_required'; end if;
  if nullif(btrim(target_reason),'') is null or length(btrim(target_reason)) not between 5 and 500 then raise exception 'recovery_reason_length_invalid'; end if;
  select * into attachment from public.line_attachments where id=target_attachment_id and company_id=company for update;
  if attachment.id is null then raise exception 'attachment_not_found'; end if;
  update public.document_original_recovery_grants grant_row
  set status='expired'
  where grant_row.company_id=company and grant_row.attachment_id=attachment.id
    and grant_row.status in ('pending','approved') and grant_row.expires_at<=now();
  insert into public.document_original_recovery_audit(company_id,grant_id,event_key,actor_id,event_data)
  select company,grant_row.id,'expired',auth.uid(),jsonb_build_object('expired_at',now())
  from public.document_original_recovery_grants grant_row
  where grant_row.company_id=company and grant_row.attachment_id=attachment.id and grant_row.status='expired'
  on conflict(grant_id,event_key) do nothing;
  select * into result from public.document_original_recovery_grants grant_row
  where grant_row.company_id=company and grant_row.attachment_id=attachment.id
    and grant_row.status in ('pending','approved') and grant_row.expires_at>now()
  order by grant_row.created_at desc limit 1;
  if result.id is not null then return result; end if;
  insert into public.document_original_recovery_grants(company_id,attachment_id,requested_by,reason,storage_bucket,storage_path,content_sha256,expires_at)
  values(company,attachment.id,auth.uid(),btrim(target_reason),attachment.storage_bucket,attachment.storage_path,attachment.content_sha256,now()+interval '15 minutes')
  returning * into result;
  insert into public.document_original_recovery_audit(company_id,grant_id,event_key,actor_id,event_data)
  values(company,result.id,'requested',auth.uid(),jsonb_build_object('attachment_id',attachment.id,'content_sha256',attachment.content_sha256));
  return result;
end $$;
revoke all on function public.request_document_original_recovery(uuid,text) from public, anon;
grant execute on function public.request_document_original_recovery(uuid,text) to authenticated;

create or replace function public.decide_document_original_recovery(target_grant_id uuid, target_decision text)
returns public.document_original_recovery_grants
language plpgsql security definer set search_path = public, pg_temp
as $$
declare company uuid := public.current_company_id(); result public.document_original_recovery_grants; next_status text;
begin
  if company is null or (not public.is_platform_admin() and not public.is_company_manager(company)) then raise exception 'admin_approval_required'; end if;
  if target_decision not in ('approved','rejected','revoked') then raise exception 'invalid_recovery_decision'; end if;
  select * into result from public.document_original_recovery_grants
  where id=target_grant_id and company_id=company and status=target_decision;
  if result.id is not null then return result; end if;
  update public.document_original_recovery_grants
  set status=target_decision, approved_by=case when target_decision='approved' then auth.uid() else approved_by end,
      approved_at=case when target_decision='approved' then now() else approved_at end,
      expires_at=case when target_decision='approved' then now()+interval '15 minutes' else expires_at end
  where id=target_grant_id and company_id=company
    and (
      (target_decision in ('approved','rejected') and status='pending' and expires_at>now())
      or (target_decision='revoked' and status in ('pending','approved'))
    )
  returning * into result;
  if result.id is null then raise exception 'recovery_grant_not_pending_or_expired'; end if;
  insert into public.document_original_recovery_audit(company_id,grant_id,event_key,actor_id,event_data)
  values(company,result.id,target_decision,auth.uid(),jsonb_build_object('expires_at',result.expires_at));
  return result;
end $$;
revoke all on function public.decide_document_original_recovery(uuid,text) from public, anon;
grant execute on function public.decide_document_original_recovery(uuid,text) to authenticated;

create or replace function public.consume_document_original_recovery(target_grant_id uuid)
returns table(storage_bucket text, storage_path text, content_sha256 text, expires_at timestamptz)
language plpgsql security definer set search_path = public, pg_temp
as $$
declare company uuid := public.current_company_id(); grant_row public.document_original_recovery_grants;
begin
  if company is null or not public.is_document_operations(company) then raise exception 'document_operations_permission_required'; end if;
  update public.document_original_recovery_grants grant_record
  set status='used', used_at=now()
  where grant_record.id=target_grant_id and grant_record.company_id=company
    and grant_record.status='approved' and grant_record.expires_at>now()
  returning * into grant_row;
  if grant_row.id is null then raise exception 'recovery_grant_not_approved_or_expired'; end if;
  insert into public.document_original_recovery_audit(company_id,grant_id,event_key,actor_id,event_data)
  values(company,grant_row.id,'consumed',auth.uid(),jsonb_build_object('used_at',now()));
  return query select grant_row.storage_bucket,grant_row.storage_path,grant_row.content_sha256,grant_row.expires_at;
end $$;
revoke all on function public.consume_document_original_recovery(uuid) from public, anon;
grant execute on function public.consume_document_original_recovery(uuid) to authenticated;

-- Replace the historical broad attachment read policy with tenant + role scope.
drop policy if exists "Authenticated users can read line attachments" on public.line_attachments;
drop policy if exists "Users can read line attachments in their company" on public.line_attachments;
drop policy if exists "tenant_isolation_line_attachments" on public.line_attachments;
create policy "Document operations read line attachments in their company"
  on public.line_attachments for select to authenticated
  using (company_id = public.current_company_id() and public.is_document_operations(company_id));

create table if not exists public.document_custody_exceptions (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  attachment_id uuid not null references public.line_attachments(id) on delete restrict,
  reason text not null,
  status text not null default 'open' check (status in ('open','resolved','waived')),
  created_at timestamptz not null default now(),
  unique(company_id, attachment_id, reason)
);
alter table public.document_custody_exceptions enable row level security;
create policy "Document operations read custody exceptions" on public.document_custody_exceptions
  for select to authenticated using(company_id=public.current_company_id() and public.is_document_operations(company_id));
revoke insert, update, delete on public.document_custody_exceptions from anon, authenticated;

create or replace function public.backfill_document_custody_metadata(target_limit integer default 500)
returns table(updated_count integer, exception_count integer)
language plpgsql security definer set search_path = public, pg_temp
as $$
declare row_item record; updated integer:=0; exceptions integer:=0; affected integer:=0; retain_date date;
begin
  if not public.is_platform_admin() then raise exception 'platform_admin_permission_required'; end if;
  for row_item in
    select attachment.*
    from public.line_attachments attachment
    where attachment.company_id is not null and (
      (attachment.retain_until is null and attachment.retention_class in ('financial','temporary','work_evidence'))
      or ((nullif(btrim(attachment.storage_path),'') is null or attachment.content_type is null or attachment.content_sha256 is null or attachment.blob_id is null)
        and not exists(select 1 from public.document_custody_exceptions exception_row
          where exception_row.company_id=attachment.company_id and exception_row.attachment_id=attachment.id and exception_row.status='open'))
    )
    order by attachment.created_at,attachment.id
    limit least(greatest(target_limit,1),5000)
  loop
    if row_item.retain_until is null and row_item.retention_class in ('financial','temporary','work_evidence') then
      retain_date := case
        when row_item.retention_class='financial' then (date_trunc('year',row_item.created_at) + interval '8 years - 1 day')::date
        else (row_item.created_at + interval '2 years')::date
      end;
      update public.line_attachments set retain_until=retain_date where id=row_item.id and retain_until is null;
      get diagnostics affected = row_count;
      updated:=updated+affected;
    end if;
    if nullif(btrim(row_item.storage_path),'') is null or row_item.content_type is null or row_item.content_sha256 is null or row_item.blob_id is null then
      insert into public.document_custody_exceptions(company_id,attachment_id,reason)
      values(row_item.company_id,row_item.id,'missing_integrity_metadata') on conflict do nothing;
      get diagnostics affected = row_count;
      exceptions:=exceptions+affected;
    end if;
  end loop;
  return query select updated,exceptions;
end $$;
revoke all on function public.backfill_document_custody_metadata(integer) from public, anon, authenticated;
grant execute on function public.backfill_document_custody_metadata(integer) to service_role;

notify pgrst, 'reload schema';
