-- SYS-009: one authoritative work list for Web, LINE and automation.

create table if not exists public.system_work_items (
  work_key text primary key,
  company_id uuid references public.companies(id) on delete cascade,
  scope text not null default 'platform' check(scope in ('platform','company')),
  title text not null,
  category text not null check(category in ('automation','line','report','audit','tenant','operations')),
  status text not null check(status in ('ready','doing','review','done','blocked')),
  progress smallint not null default 0 check(progress between 0 and 100),
  risk text not null check(risk in ('low','medium','high','critical')),
  detail text,
  production_status text not null default 'not_deployed',
  owner text,
  evidence text,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check((scope='platform' and company_id is null) or (scope='company' and company_id is not null))
);

create table if not exists public.system_work_item_events (
  id bigint generated by default as identity primary key,
  work_key text not null references public.system_work_items(work_key) on delete cascade,
  company_id uuid references public.companies(id) on delete cascade,
  event_type text not null,
  old_status text,
  new_status text,
  old_progress smallint,
  new_progress smallint,
  note text,
  actor_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists system_work_items_status_idx on public.system_work_items(status,category,work_key);
create index if not exists system_work_items_company_idx on public.system_work_items(company_id,status) where company_id is not null;
create index if not exists system_work_item_events_key_idx on public.system_work_item_events(work_key,created_at desc);

create or replace function public.audit_system_work_item_change()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if tg_op='INSERT' then
    insert into public.system_work_item_events(work_key,company_id,event_type,new_status,new_progress,note,actor_id)
    values(new.work_key,new.company_id,'created',new.status,new.progress,new.detail,auth.uid());
  elsif old.status is distinct from new.status or old.progress is distinct from new.progress or old.detail is distinct from new.detail or old.production_status is distinct from new.production_status then
    insert into public.system_work_item_events(work_key,company_id,event_type,old_status,new_status,old_progress,new_progress,note,actor_id)
    values(new.work_key,new.company_id,'updated',old.status,new.status,old.progress,new.progress,new.evidence,auth.uid());
  end if;
  return null;
end $$;

drop trigger if exists audit_system_work_item_change_trigger on public.system_work_items;
create trigger audit_system_work_item_change_trigger after insert or update on public.system_work_items
for each row execute function public.audit_system_work_item_change();

alter table public.system_work_items enable row level security;
alter table public.system_work_item_events enable row level security;

create policy "Authorized users read system work items" on public.system_work_items for select to authenticated using(
  (scope='platform' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
  or (scope='company' and public.is_company_member(company_id))
);
create policy "Authorized managers update system work items" on public.system_work_items for update to authenticated using(
  (scope='platform' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
  or (scope='company' and public.is_company_manager(company_id))
) with check(
  (scope='platform' and company_id is null and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
  or (scope='company' and public.is_company_manager(company_id))
);
create policy "Authorized users read system work history" on public.system_work_item_events for select to authenticated using(
  exists(select 1 from public.system_work_items item where item.work_key=system_work_item_events.work_key)
);

revoke insert,delete on public.system_work_items from anon,authenticated;
revoke insert,update,delete on public.system_work_item_events from anon,authenticated;

insert into public.system_work_items(work_key,title,category,status,progress,risk,detail,production_status) values
('SYS-001','หน้า Status แบบกราฟิก','report','review',90,'low','รอผู้ใช้ตรวจหน้าจริงและยืนยันการแสดงผล','deployed'),
('SYS-002','Scheduled Monitor เบื้องหลัง 24 ชั่วโมง','automation','ready',25,'high','ตรวจได้แม้ไม่มี Admin เปิดเว็บและไม่เปิดเผย Secret','not_deployed'),
('SYS-003','LINE heartbeat ตรวจกรณีส่งแล้วเงียบ','line','done',100,'high','Webhook แยกบริษัทและผ่าน Production UAT','deployed'),
('SYS-004','ตรวจจับ Error และสร้างงานแก้ไขอัตโนมัติ','automation','ready',35,'medium','รวม fingerprint, severity, SLA และวงจรแก้ไข','not_deployed'),
('SYS-005','ศูนย์สั่งงานผ่านมือถือและคอมพิวเตอร์','report','ready',10,'medium','สร้างคำสั่ง ติดตาม อนุมัติ และเก็บ audit log','not_deployed'),
('SYS-006','ตรวจงานค้างด้วย Worker heartbeat','automation','ready',10,'medium','ตรวจ heartbeat, stale และ timeout','not_deployed'),
('SYS-007','ส่งรายงาน Status เข้ากลุ่ม LINE','line','review',90,'medium','ส่งสถานะจากฐานข้อมูลกลางและป้องกันส่งซ้ำ','deployed'),
('SYS-008','ศูนย์สั่งงานผ่าน LINE และ Voice','line','review',90,'high','รอ Voice UAT จริงจาก LINE','deployed'),
('SYS-009','Single source of truth สำหรับรายการงาน','automation','doing',70,'high','ฐานข้อมูลกลางสำหรับ Web, LINE, Automation และ audit','not_deployed'),
('OPS-001','บันทึกงานที่ยืนยันลง List และรายงาน Status','operations','done',100,'low','ใช้ workflow รายการงานกลาง','deployed'),
('AUD-001','ตรวจผลกระทบ Multi-company Migration ทุกโมดูล','audit','review',75,'high','พบงานแก้ tenant isolation 12 งาน','not_deployed'),
('TEN-001','ซ่อม Attendance Edge ให้กรองบริษัทครบ','tenant','review',90,'critical','รอ UAT เข้า ออก GPS เครื่องร่วม และลงซ้ำ','deployed'),
('TEN-002','ซ่อม Attendance Reminder รอบ 20:00/00:00/07:00','tenant','review',95,'critical','Cron ผ่าน Vault พร้อมแล้ว รอตรวจรอบเวลาจริง','deployed'),
('TEN-003','ซ่อม Drawing AI Edge และผลวิเคราะห์','tenant','ready',0,'high','เพิ่ม company scope ทุก query และ write','not_deployed'),
('TEN-004','ซ่อมการเพิ่มพนักงานและผูกสมาชิกบริษัท','tenant','ready',0,'critical','สร้าง employee และ company membership ให้ครบ','not_deployed'),
('TEN-005','ป้องกันจัดการพนักงานข้ามบริษัท','tenant','ready',0,'critical','ตรวจ company admin ก่อนแตะ Auth Admin','not_deployed'),
('TEN-006','แยก Config singleton ต่อบริษัท','tenant','ready',0,'high','ปรับ schema และหน้า Config ให้แยกบริษัท','not_deployed'),
('TEN-007','รองรับการจ้างงานพนักงานหลายบริษัท','tenant','ready',0,'high','แยกค่าจ้าง ประเภทจ้าง และสถานะต่อบริษัท','not_deployed'),
('TEN-008','อุด Tenant boundary ใน RPC และ Trigger','tenant','ready',0,'critical','เพิ่ม company predicate และ regression test','not_deployed'),
('TEN-009','แยก Storage path และสิทธิ์ไฟล์ต่อบริษัท','tenant','ready',0,'critical','บังคับ company namespace ในทุก bucket','not_deployed'),
('TEN-010','แยก Health Monitor และ LINE ปลายทางต่อบริษัท','tenant','ready',0,'high','แยก monitor กลางและรายบริษัท','not_deployed'),
('TEN-011','ซ่อม LINE Account Link สำหรับหลายบริษัท','tenant','ready',0,'high','เพิ่ม company scope และ UAT การผูกบัญชี','not_deployed'),
('TEN-012','Multi-company Regression Test ทุกโมดูล','tenant','ready',0,'high','ทดสอบอย่างน้อยสองบริษัทและ cross-tenant negative cases','not_deployed')
on conflict(work_key) do nothing;

comment on table public.system_work_items is 'Authoritative work status source consumed by Web, LINE and automation.';
