-- Guarded, replay-safe Phase 3 activation. Any drift aborts atomically.
do $$
declare item public.system_work_items; target record; expected_fingerprint text; already_final boolean := true;
  receipt constant text := 'CTRL-POSTING-PHASE2-5-20260916';
begin
  perform 1 from public.system_work_items where work_key in ('POSTING-001','POSTING-002','POSTING-004','POSTING-005','POSTING-008','FILTER-004','FILTER-007','FILTER-008') order by work_key for update;
  if (select count(*) from public.system_work_items where work_key in ('POSTING-001','POSTING-002','POSTING-004','POSTING-005','POSTING-008','FILTER-004','FILTER-007','FILTER-008')) <> 8 then raise exception 'Posting Phase 3 activation refused: approved batch is incomplete'; end if;
  for target in select * from (values ('POSTING-001',2),('POSTING-002',2),('POSTING-004',3),('POSTING-005',3),('POSTING-008',4),('FILTER-004',5),('FILTER-007',5),('FILTER-008',5)) as planned(work_key,phase) loop
    select * into item from public.system_work_items where work_key=target.work_key;
    expected_fingerprint := public.system_work_item_scope_fingerprint(item.work_key,item.title,item.category,item.risk,item.detail);
    if item.worker_id is not null or item.approval_status <> 'approved' or item.approval_fingerprint is distinct from expected_fingerprint or item.context_manifest ->> 'batch_approval_receipt' <> receipt or (item.context_manifest ->> 'execution_phase')::integer <> target.phase then raise exception '% approval/scope/receipt/worker guard failed',target.work_key; end if;
    if not ((target.work_key in ('POSTING-001','POSTING-002') and item.status='done' and item.progress=100 and item.control_state='done' and item.production_status='phase2_verified_production') or (target.work_key in ('POSTING-004','POSTING-005') and item.status='ready' and item.progress=0 and item.control_state='queued' and item.production_status='approved_for_execution') or (target.phase >= 4 and item.status='blocked' and item.progress=0 and item.control_state='blocked' and item.production_status='approved_waiting_dependency' and item.context_manifest ->> 'phase_gate'='waiting_dependency')) then already_final := false; end if;
  end loop;
  if already_final then return; end if;
  select * into item from public.system_work_items where work_key='POSTING-001';
  if item.status <> 'blocked' or item.progress <> 80 or item.production_status <> 'local_verified_not_deployed' or item.control_state <> 'blocked' then raise exception 'POSTING-001 Phase 2 state changed; Phase 3 activation refused'; end if;
  select * into item from public.system_work_items where work_key='POSTING-002';
  if item.status <> 'review' or item.progress <> 90 or item.production_status <> 'local_verified_waiting_independent_qa' or item.control_state <> 'waiting_qa' then raise exception 'POSTING-002 Phase 2 state changed; Phase 3 activation refused'; end if;
  for target in select * from (values ('POSTING-004',3),('POSTING-005',3),('POSTING-008',4),('FILTER-004',5),('FILTER-007',5),('FILTER-008',5)) as planned(work_key,phase) loop
    select * into item from public.system_work_items where work_key=target.work_key;
    if item.status <> 'blocked' or item.progress <> 0 or item.production_status <> 'approved_waiting_dependency' or item.control_state <> 'blocked' or item.context_manifest ->> 'phase_gate' <> 'waiting_dependency' then raise exception '% dependency state changed; Phase 3 activation refused',target.work_key; end if;
  end loop;
  update public.system_work_items set status='done',progress=100,control_state='done',production_status='phase2_verified_production',current_step='Phase 2 verified in Production; Phase 3 dependency released.',blocked_since=null,context_manifest=context_manifest || jsonb_build_object('phase_gate','complete','production_commit','13acc9ba9ccdf973b12ff0a28bc749ef9c5de5df','production_revision','13acc9b','migration_run','35111437758','phase3_activation_receipt','CTRL-POSTING-PHASE3-20260916'),evidence=left(concat_ws(E'\n',nullif(evidence,''),'Phase 2 Production verified: PR #102, commit 13acc9ba9ccdf973b12ff0a28bc749ef9c5de5df, Cloudflare 13acc9b, migration run 35111437758 succeeded.'),4000),updated_at=now() where work_key='POSTING-001';
  update public.system_work_items set status='done',progress=100,control_state='done',production_status='phase2_verified_production',current_step='Phase 2 independent QA passed; Phase 3 dependency released.',blocked_since=null,context_manifest=context_manifest || jsonb_build_object('phase_gate','complete','production_commit','b2e54cde0e2c03aaf6e87261b47d73f361ca52d3','production_revision','b2e54cd','independent_qa','passed_after_fixes','phase3_activation_receipt','CTRL-POSTING-PHASE3-20260916'),evidence=left(concat_ws(E'\n',nullif(evidence,''),'Phase 2 Production verified: PR #103, commit b2e54cde0e2c03aaf6e87261b47d73f361ca52d3, Cloudflare b2e54cd; independent QA passed after fixes.'),4000),updated_at=now() where work_key='POSTING-002';
  update public.system_work_items set status='ready',progress=0,control_state='queued',production_status='approved_for_execution',current_step='Phase 2 Production and independent QA verified; Phase 3 ready for atomic Worker claim.',blocked_since=null,context_manifest=context_manifest || jsonb_build_object('phase_gate','released','phase3_activation_receipt','CTRL-POSTING-PHASE3-20260916'),evidence=left(concat_ws(E'\n',nullif(evidence,''),'Phase 3 released only after guarded verification of POSTING-001 and POSTING-002.'),4000),updated_at=now() where work_key in ('POSTING-004','POSTING-005');
  insert into public.system_work_item_events(work_key,company_id,event_type,old_status,new_status,old_progress,new_progress,note)
  select work_key,company_id,'posting_phase3_activated',case when work_key in ('POSTING-001','POSTING-004','POSTING-005') then 'blocked' else 'review' end,status,case when work_key='POSTING-001' then 80 when work_key='POSTING-002' then 90 else 0 end,progress,'CTRL-POSTING-PHASE3-20260916; guarded Production/QA evidence recorded' from public.system_work_items where work_key in ('POSTING-001','POSTING-002','POSTING-004','POSTING-005');
end $$;
