-- Durable evidence links, historical LINE screenshot classification and storage policy metadata.
alter table public.line_attachments
  add column if not exists retention_class text not null default 'temporary'
    check(retention_class in ('temporary','work_evidence','system_error','financial','audit')),
  add column if not exists retain_until date,
  add column if not exists optimized_at timestamptz,
  add column if not exists original_size_bytes bigint;

update public.line_attachments set original_size_bytes=size_bytes where original_size_bytes is null;

create table if not exists public.system_error_evidence (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  error_event_id uuid not null references public.system_error_events(id) on delete cascade,
  message_id uuid not null references public.line_messages(id) on delete cascade,
  attachment_id uuid references public.line_attachments(id) on delete set null,
  source text not null default 'line_user_screenshot',
  match_method text not null default 'automatic',
  confidence numeric(5,4),
  created_at timestamptz not null default now(),
  unique(company_id,message_id)
);
create index if not exists system_error_evidence_event_idx on public.system_error_evidence(error_event_id,created_at desc);
alter table public.system_error_evidence enable row level security;
drop policy if exists "Managers read system error evidence" on public.system_error_evidence;
create policy "Managers read system error evidence" on public.system_error_evidence
for select to authenticated using(public.is_company_manager(company_id));
revoke insert,update,delete on public.system_error_evidence from anon,authenticated;

-- Preserve existing single-evidence links in the new one-to-many register.
insert into public.system_error_evidence(company_id,error_event_id,message_id,attachment_id,match_method)
select event.company_id,event.id,event.last_evidence_message_id,attachment.id,'legacy_link'
from public.system_error_events event
left join public.line_attachments attachment on attachment.message_id=event.last_evidence_message_id
where event.last_evidence_message_id is not null
on conflict(company_id,message_id) do nothing;

-- Reclassify every historical LINE image where the stored vision result already
-- identified a software error with production confidence.
update public.image_review_cases review
set proposed_primary_purpose='system_error',updated_at=now()
where coalesce((review.proposed_output->'system_error'->>'is_system_error')::boolean,false)
  and coalesce((review.proposed_output->'system_error'->>'confidence')::numeric,review.ai_confidence,0)>=0.65;

do $$
declare candidate record; matched_event uuid;
begin
  for candidate in
    select review.id review_id,review.company_id,review.source_message_id,review.attachment_id,review.ai_confidence,
      message.occurred_at,coalesce(nullif(review.proposed_output->'system_error'->>'affected_module',''),'unknown_module') affected_module,
      nullif(review.proposed_output->'system_error'->>'error_code','') error_code,
      coalesce(nullif(review.proposed_output->'system_error'->>'visible_message',''),'ผู้ใช้ส่งภาพแจ้ง Error ระบบผ่าน LINE') visible_message
    from public.image_review_cases review
    join public.line_messages message on message.id=review.source_message_id
    where review.proposed_primary_purpose='system_error'
      and not exists(select 1 from public.system_error_evidence evidence where evidence.company_id=review.company_id and evidence.message_id=review.source_message_id)
  loop
    select event.id into matched_event from public.system_error_events event
    where event.company_id=candidate.company_id
      and event.first_seen_at between candidate.occurred_at-interval '30 days' and candidate.occurred_at+interval '30 days'
      and (lower(coalesce(event.affected_module,''))=lower(candidate.affected_module)
        or (candidate.error_code is not null and lower(coalesce(event.metadata->>'error_code',''))=lower(candidate.error_code)))
    order by abs(extract(epoch from event.first_seen_at-candidate.occurred_at)) limit 1;

    if matched_event is null then
      insert into public.system_error_events(company_id,fingerprint,correlation_key,severity,status,title,message,affected_module,
        first_source,occurrence_count,system_occurrence_count,user_report_count,confirmed_by_user_at,last_evidence_message_id,
        metadata,first_seen_at,last_seen_at,resolution_reason,resolved_at)
      values(candidate.company_id,'line-history:'||substr(md5(candidate.source_message_id::text),1,24),
        lower(candidate.affected_module||'|'||coalesce(candidate.error_code,'visible_error')||'|'||candidate.visible_message),
        'error','resolved','ผู้ใช้แจ้ง Error ระบบ: '||candidate.affected_module,candidate.visible_message,candidate.affected_module,
        'line_user_screenshot',1,0,1,candidate.occurred_at,candidate.source_message_id,
        jsonb_build_object('error_code',candidate.error_code,'review_case_id',candidate.review_id,'historical_import',true),
        candidate.occurred_at,candidate.occurred_at,'นำเข้าหลักฐานย้อนหลัง ไม่ใช่เหตุขัดข้องปัจจุบัน',now())
      returning id into matched_event;
    else
      update public.system_error_events set occurrence_count=occurrence_count+1,user_report_count=user_report_count+1,
        confirmed_by_user_at=coalesce(confirmed_by_user_at,candidate.occurred_at),last_evidence_message_id=candidate.source_message_id,
        metadata=metadata||jsonb_build_object('historical_evidence_linked',true),updated_at=now()
      where id=matched_event;
    end if;

    insert into public.system_error_evidence(company_id,error_event_id,message_id,attachment_id,match_method,confidence)
    values(candidate.company_id,matched_event,candidate.source_message_id,candidate.attachment_id,
      case when candidate.error_code is null then 'module_and_time' else 'error_code_module_time' end,candidate.ai_confidence)
    on conflict(company_id,message_id) do nothing;
    update public.line_attachments set retention_class='system_error',retain_until=null
    where id=candidate.attachment_id;
  end loop;
end $$;

create or replace function public.register_reviewed_system_error_image(target_case_id uuid,target_note text default null)
returns public.system_error_events
language plpgsql security definer set search_path=public as $$
declare company uuid:=public.current_company_id(); review_row public.image_review_cases; error_payload jsonb;
  error_code text; visible_message text; affected_module text; result public.system_error_events;
begin
  if company is null or not public.is_company_manager(company) then raise exception 'manager access required'; end if;
  select * into review_row from public.image_review_cases where id=target_case_id and company_id=company for update;
  if review_row.id is null then raise exception 'image review not found'; end if;
  if review_row.review_status not in ('confirmed','corrected') or review_row.confirmed_primary_purpose<>'system_error' then raise exception 'image must be confirmed as system_error first'; end if;
  error_payload:=coalesce(review_row.confirmed_output,review_row.proposed_output,'{}'::jsonb)->'system_error';
  error_code:=nullif(trim(coalesce(error_payload->>'error_code','')),'');
  visible_message:=coalesce(nullif(trim(coalesce(error_payload->>'visible_message','')),''),nullif(trim(coalesce(target_note,'')),''),'ผู้ใช้ส่งภาพแจ้ง Error ระบบผ่าน LINE');
  affected_module:=coalesce(nullif(trim(coalesce(error_payload->>'affected_module','')),''),'unknown_module');
  select * into result from public.upsert_system_error_event(company,'line-image:'||substr(md5(review_row.source_message_id::text||'|'||coalesce(error_code,affected_module)),1,24),
    lower(affected_module||'|'||coalesce(error_code,'visible_error')||'|'||visible_message),'line_user_screenshot','ผู้ใช้แจ้ง Error ระบบ: '||affected_module,
    visible_message,affected_module,'error',jsonb_build_object('error_code',error_code,'review_case_id',review_row.id,'confirmed_by',auth.uid()),review_row.source_message_id,true);
  insert into public.system_error_evidence(company_id,error_event_id,message_id,attachment_id,match_method,confidence)
  values(company,result.id,review_row.source_message_id,review_row.attachment_id,'manual_review',review_row.ai_confidence)
  on conflict(company_id,message_id) do update set error_event_id=excluded.error_event_id,attachment_id=excluded.attachment_id,match_method='manual_review';
  update public.line_attachments set retention_class='system_error',retain_until=null where id=review_row.attachment_id;
  return result;
end $$;
revoke all on function public.register_reviewed_system_error_image(uuid,text) from public,anon;
grant execute on function public.register_reviewed_system_error_image(uuid,text) to authenticated;

create or replace view public.line_image_storage_report with (security_invoker=true) as
select attachment.company_id,attachment.retention_class,count(*) file_count,
  coalesce(sum(attachment.size_bytes),0) stored_bytes,
  coalesce(sum(case when attachment.duplicate_of is not null then attachment.size_bytes else 0 end),0) reclaimable_duplicate_bytes,
  min(attachment.created_at) oldest_file_at,max(attachment.created_at) newest_file_at
from public.line_attachments attachment group by attachment.company_id,attachment.retention_class;
grant select on public.line_image_storage_report to authenticated;

update public.system_work_items
set status='review',
    progress=90,
    risk='medium',
    current_step='verify_line_screenshot_evidence_correlation',
    evidence='SYS-004 source verification: tenant-scoped error intake deduplicates concurrent events atomically by company and fingerprint, correlates confirmed and historical LINE screenshots through durable evidence links, and retains the original incident/work-item history. Passed test:error-fingerprint, test:system-error-intake, test:problem-register, lint, and build on 2026-08-15; Production migration and authenticated UAT were not run in this work item.',
    production_status='source_verified_not_deployed',
    updated_at=now()
where work_key='SYS-004';

notify pgrst,'reload schema';
