-- Separate company access from employee/attendance participation.
alter table public.company_members
  add column if not exists member_type text not null default 'employee'
  check(member_type in ('admin_only','employee','admin_employee'));

-- The reference-boundary trigger only needs to re-check identity/tenant keys.
-- Restricting UPDATE events to those keys lets ordinary member attributes be
-- maintained by audited RPCs without weakening INSERT or cross-company guards.
drop trigger if exists enforce_company_reference_boundary on public.company_members;
create trigger enforce_company_reference_boundary
before insert or update of company_id,profile_id on public.company_members
for each row execute function public.enforce_company_reference_boundary();

update public.company_members member
set member_type=case
  when exists(select 1 from public.employee_employment_records employment where employment.company_id=member.company_id and employment.profile_id=member.profile_id)
    then case when member.company_role in ('company_admin','executive','manager') then 'admin_employee' else 'employee' end
  when member.company_role in ('company_admin','executive','manager') then 'admin_only'
  else 'employee'
end;

create table if not exists public.company_member_type_audit (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  old_member_type text,
  new_member_type text not null,
  reason text not null,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.company_member_type_audit enable row level security;
create policy "Managers read member type audit" on public.company_member_type_audit
for select to authenticated using(public.is_company_manager(company_id));
revoke insert,update,delete on public.company_member_type_audit from anon,authenticated;

create or replace function public.update_company_member_type(target_profile_id uuid,target_member_type text,target_reason text)
returns public.company_members language plpgsql security definer set search_path=public as $$
declare company uuid:=public.current_company_id(); before_row public.company_members; result public.company_members;
begin
  if not public.is_company_manager(company) then raise exception 'manager access required'; end if;
  if target_member_type not in ('admin_only','employee','admin_employee') then raise exception 'invalid member type'; end if;
  if length(trim(coalesce(target_reason,'')))<5 then raise exception 'reason is required'; end if;
  select * into before_row from public.company_members where company_id=company and profile_id=target_profile_id for update;
  if before_row.profile_id is null then raise exception 'member not found'; end if;
  if target_member_type='admin_only' and before_row.company_role not in ('company_admin','executive','manager') then
    raise exception 'admin_only requires an administrator role';
  end if;
  update public.company_members set member_type=target_member_type,updated_at=now()
  where company_id=company and profile_id=target_profile_id returning * into result;
  insert into public.company_member_type_audit(company_id,profile_id,old_member_type,new_member_type,reason,actor_profile_id)
  values(company,target_profile_id,before_row.member_type,target_member_type,left(trim(target_reason),500),auth.uid());
  return result;
end $$;
revoke all on function public.update_company_member_type(uuid,text,text) from public,anon;
grant execute on function public.update_company_member_type(uuid,text,text) to authenticated;

create or replace view public.employee_onboarding_readiness with (security_invoker=true) as
select profile.id profile_id,profile.full_name,profile.email,employment.employee_code,employment.employment_status,
  (nullif(trim(profile.full_name),'') is not null) has_name,(employment.profile_id is not null) has_employment,
  (case when employment.employment_type='monthly' then employment.monthly_salary>0 else employment.daily_rate>0 end) has_pay_rate,
  (employment.overtime_hourly_rate>0) has_ot_rate,coalesce(assignments.all_sites_have_policy,false) has_work_policy,
  (coalesce(assignments.site_count,0)>0) has_site,
  (nullif(trim(profile.full_name),'') is not null and employment.profile_id is not null
    and case when employment.employment_type='monthly' then employment.monthly_salary>0 else employment.daily_rate>0 end
    and coalesce(assignments.all_sites_have_policy,false) and coalesce(assignments.site_count,0)>0) ready_to_clock,
  member.company_id,coalesce(assignments.site_count,0)::integer active_site_count,
  case when employment.work_policy_id is not null then 'employee'
    when assignments.has_assignment_policy then 'assignment'
    when assignments.has_site_policy then 'site' else 'none' end policy_source,
  member.member_type
from public.company_members member join public.profiles profile on profile.id=member.profile_id
left join public.employee_employment_records employment on employment.company_id=member.company_id and employment.profile_id=profile.id
left join lateral (
  select count(*) site_count,
    bool_and(coalesce(site_assignment.work_policy_id,employment.work_policy_id,site.work_policy_id) is not null) all_sites_have_policy,
    bool_or(site_assignment.work_policy_id is not null) has_assignment_policy,
    bool_or(site_assignment.work_policy_id is null and site.work_policy_id is not null) has_site_policy
  from public.employee_site_assignments site_assignment
  join public.project_sites site on site.id=site_assignment.site_id and site.company_id=member.company_id
  where site_assignment.company_id=member.company_id and site_assignment.profile_id=profile.id and site_assignment.active
    and site_assignment.starts_on<=current_date and (site_assignment.ends_on is null or site_assignment.ends_on>=current_date)
) assignments on true
where member.active=true and member.member_type in ('employee','admin_employee');
grant select on public.employee_onboarding_readiness to authenticated;
