-- WORK-CONTROL-CORE-V2
-- Additive cost/model routing controls. Defaults preserve the v1 execution path.

alter table public.system_work_items
  add column if not exists model_tier text not null default 'balanced',
  add column if not exists model_name text,
  add column if not exists token_budget_input integer not null default 24000,
  add column if not exists token_budget_output integer not null default 6000,
  add column if not exists token_soft_limit_percent integer not null default 80,
  add column if not exists token_input_total bigint not null default 0,
  add column if not exists token_output_total bigint not null default 0,
  add column if not exists estimated_cost_usd numeric(14,6) not null default 0,
  add column if not exists actual_cost_usd numeric(14,6) not null default 0,
  add column if not exists prompt_version text not null default 'work-control-v2',
  add column if not exists output_schema_version text not null default '2',
  add column if not exists qa_tier text not null default 'standard',
  add column if not exists escalation_level smallint not null default 0,
  add column if not exists cache_key text,
  add column if not exists cache_hit boolean not null default false,
  add column if not exists resource_keys text[] not null default '{}'::text[];

alter table public.system_work_items drop constraint if exists system_work_items_model_tier_check;
alter table public.system_work_items add constraint system_work_items_model_tier_check check (model_tier in ('economy','balanced','reasoning'));
alter table public.system_work_items drop constraint if exists system_work_items_qa_tier_check;
alter table public.system_work_items add constraint system_work_items_qa_tier_check check (qa_tier in ('automated','standard','independent','human'));
alter table public.system_work_items drop constraint if exists system_work_items_token_budget_check;
alter table public.system_work_items add constraint system_work_items_token_budget_check check (
  token_budget_input between 1000 and 1000000 and token_budget_output between 500 and 250000
  and token_soft_limit_percent between 50 and 95 and escalation_level between 0 and 3
);

alter table public.system_worker_runs
  add column if not exists model_tier text,
  add column if not exists model_name text,
  add column if not exists token_budget_input integer,
  add column if not exists token_budget_output integer,
  add column if not exists prompt_version text,
  add column if not exists output_schema_version text,
  add column if not exists cache_key text,
  add column if not exists cache_hit boolean not null default false,
  add column if not exists estimated_cost_usd numeric(14,6) not null default 0,
  add column if not exists actual_cost_usd numeric(14,6) not null default 0;

create table if not exists public.system_model_policies (
  id bigint generated by default as identity primary key,
  company_id uuid references public.companies(id) on delete cascade,
  category text,
  risk text,
  model_tier text not null check(model_tier in ('economy','balanced','reasoning')),
  model_name text,
  token_budget_input integer not null,
  token_budget_output integer not null,
  token_soft_limit_percent integer not null default 80 check(token_soft_limit_percent between 50 and 95),
  qa_tier text not null check(qa_tier in ('automated','standard','independent','human')),
  max_concurrency integer not null default 1 check(max_concurrency between 1 and 20),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists system_model_policies_scope_idx on public.system_model_policies(
  coalesce(company_id,'00000000-0000-0000-0000-000000000000'::uuid),coalesce(category,'*'),coalesce(risk,'*')
);

create table if not exists public.system_work_result_cache (
  cache_key text primary key,
  work_key text not null references public.system_work_items(work_key) on delete cascade,
  requirement_version integer not null,
  source_sha text not null,
  prompt_version text not null,
  output_schema_version text not null,
  dependency_hash text not null,
  result jsonb not null,
  evidence_refs jsonb not null default '[]'::jsonb,
  valid_until timestamptz,
  created_at timestamptz not null default now(),
  last_hit_at timestamptz,
  hit_count integer not null default 0
);

create table if not exists public.system_work_cost_events (
  id bigint generated by default as identity primary key,
  work_key text not null references public.system_work_items(work_key) on delete cascade,
  run_id uuid references public.system_worker_runs(id) on delete set null,
  company_id uuid references public.companies(id) on delete cascade,
  model_tier text not null,
  model_name text,
  token_input integer not null default 0,
  token_output integer not null default 0,
  estimated_cost_usd numeric(14,6) not null default 0,
  actual_cost_usd numeric(14,6) not null default 0,
  cache_hit boolean not null default false,
  escalation_level smallint not null default 0,
  recorded_at timestamptz not null default now()
);
create index if not exists system_work_cost_events_work_idx on public.system_work_cost_events(work_key,recorded_at desc);
create unique index if not exists system_work_cost_events_run_idx on public.system_work_cost_events(run_id) where run_id is not null;

create table if not exists public.system_work_resource_locks (
  resource_key text primary key,
  work_key text not null references public.system_work_items(work_key) on delete cascade,
  run_id uuid references public.system_worker_runs(id) on delete cascade,
  worker_id text not null,
  lease_expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.system_model_policies enable row level security;
alter table public.system_work_result_cache enable row level security;
alter table public.system_work_cost_events enable row level security;
alter table public.system_work_resource_locks enable row level security;

drop policy if exists "Authorized users read model policies" on public.system_model_policies;
create policy "Authorized users read model policies" on public.system_model_policies for select to authenticated using (
  public.is_platform_admin() or (company_id is not null and public.is_company_manager(company_id))
);
drop policy if exists "Authorized users read work cache" on public.system_work_result_cache;
create policy "Authorized users read work cache" on public.system_work_result_cache for select to authenticated using (
  exists(select 1 from public.system_work_items i where i.work_key=system_work_result_cache.work_key
    and (public.is_platform_admin() or (i.company_id is not null and public.is_company_manager(i.company_id))))
);
drop policy if exists "Authorized users read work costs" on public.system_work_cost_events;
create policy "Authorized users read work costs" on public.system_work_cost_events for select to authenticated using (
  public.is_platform_admin() or (company_id is not null and public.is_company_manager(company_id))
);
drop policy if exists "Authorized users read resource locks" on public.system_work_resource_locks;
create policy "Authorized users read resource locks" on public.system_work_resource_locks for select to authenticated using (
  exists(select 1 from public.system_work_items i where i.work_key=system_work_resource_locks.work_key
    and (public.is_platform_admin() or (i.company_id is not null and public.is_company_manager(i.company_id))))
);

revoke insert,update,delete on public.system_model_policies from anon,authenticated;
revoke insert,update,delete on public.system_work_result_cache from anon,authenticated;
revoke insert,update,delete on public.system_work_cost_events from anon,authenticated;
revoke insert,update,delete on public.system_work_resource_locks from anon,authenticated;

create or replace function public.record_system_work_cost_v2(
  target_run uuid,target_worker text,target_token_input integer,target_token_output integer,
  target_estimated_cost numeric default 0,target_actual_cost numeric default 0,target_cache_hit boolean default false
) returns boolean language plpgsql security definer set search_path=public as $$
declare r public.system_worker_runs; i public.system_work_items; inserted_count integer;
begin
  select * into r from public.system_worker_runs where id=target_run and worker_id=target_worker;
  if r.id is null then return false; end if;
  select * into i from public.system_work_items where work_key=r.work_key;
  insert into public.system_work_cost_events(work_key,run_id,company_id,model_tier,model_name,token_input,token_output,estimated_cost_usd,actual_cost_usd,cache_hit,escalation_level)
  values(i.work_key,r.id,i.company_id,i.model_tier,i.model_name,greatest(coalesce(target_token_input,0),0),greatest(coalesce(target_token_output,0),0),greatest(coalesce(target_estimated_cost,0),0),greatest(coalesce(target_actual_cost,0),0),coalesce(target_cache_hit,false),i.escalation_level)
  on conflict (run_id) where run_id is not null do nothing;
  get diagnostics inserted_count = row_count;
  if inserted_count = 0 then return true; end if;
  update public.system_worker_runs set token_input=greatest(coalesce(target_token_input,0),0),token_output=greatest(coalesce(target_token_output,0),0),
    estimated_cost_usd=greatest(coalesce(target_estimated_cost,0),0),actual_cost_usd=greatest(coalesce(target_actual_cost,0),0),cache_hit=coalesce(target_cache_hit,false) where id=r.id;
  update public.system_work_items set token_input_total=token_input_total+greatest(coalesce(target_token_input,0),0),
    token_output_total=token_output_total+greatest(coalesce(target_token_output,0),0),estimated_cost_usd=estimated_cost_usd+greatest(coalesce(target_estimated_cost,0),0),
    actual_cost_usd=actual_cost_usd+greatest(coalesce(target_actual_cost,0),0),cache_hit=coalesce(target_cache_hit,false),updated_at=now() where work_key=i.work_key;
  return true;
end $$;
revoke all on function public.record_system_work_cost_v2(uuid,text,integer,integer,numeric,numeric,boolean) from public,anon,authenticated;
grant execute on function public.record_system_work_cost_v2(uuid,text,integer,integer,numeric,numeric,boolean) to service_role;

comment on table public.system_model_policies is 'Fail-open routing/budget policy. An absent model_name keeps the runner current model.';
comment on table public.system_work_result_cache is 'Result reuse is allowed only for an exact source SHA, requirement, prompt, schema and dependency hash.';
