-- WORK-CONTROL-CORE-P0
-- Durable checkpoint, compact context and no-new-information retry guard.

alter table public.system_work_items
  add column if not exists requirement_version integer not null default 1,
  add column if not exists controller_owner text,
  add column if not exists execution_owner text,
  add column if not exists qa_owner text,
  add column if not exists control_state text not null default 'queued',
  add column if not exists checkpoint jsonb not null default '{}'::jsonb,
  add column if not exists context_manifest jsonb not null default '{}'::jsonb,
  add column if not exists new_information_hash text;

alter table public.system_work_items drop constraint if exists system_work_items_control_state_check;
alter table public.system_work_items add constraint system_work_items_control_state_check check (
  control_state in ('queued','active','blocked','paused','waiting_permission','token_limit','waiting_qa','worker_lost','done')
);

-- Reconcile legacy rows immediately so the new control plane does not present
-- completed/review/blocked work as queued merely because of the column default.
update public.system_work_items
set control_state = case
  when status = 'done' then 'done'
  when status = 'review' then 'waiting_qa'
  when status = 'blocked' then 'blocked'
  when status = 'doing' and lease_expires_at is not null and lease_expires_at > now() then 'active'
  when status = 'doing' then 'worker_lost'
  else 'queued'
end
where control_state = 'queued';

alter table public.system_worker_runs
  add column if not exists requirement_version integer,
  add column if not exists checkpoint jsonb not null default '{}'::jsonb,
  add column if not exists context_manifest_hash text,
  add column if not exists token_input integer,
  add column if not exists token_output integer,
  add column if not exists stop_reason text;

create table if not exists public.system_work_checkpoints (
  id bigint generated by default as identity primary key,
  work_key text not null references public.system_work_items(work_key) on delete cascade,
  run_id uuid references public.system_worker_runs(id) on delete set null,
  requirement_version integer not null,
  milestone text not null,
  checkpoint jsonb not null,
  context_manifest jsonb not null default '{}'::jsonb,
  evidence_refs jsonb not null default '[]'::jsonb,
  next_action text,
  created_at timestamptz not null default now()
);

create index if not exists system_work_checkpoints_latest_idx
  on public.system_work_checkpoints(work_key,requirement_version,created_at desc);

create table if not exists public.system_work_problems (
  id bigint generated by default as identity primary key,
  work_key text not null references public.system_work_items(work_key) on delete cascade,
  requirement_version integer not null,
  problem_fingerprint text not null,
  category text not null check(category in ('code','token','allow','policy','dependency','config','data','network','qa','worker_lost','unknown')),
  status text not null default 'open' check(status in ('open','resolved','escalated','cancelled')),
  retry_count integer not null default 0,
  retry_allowed boolean not null default false,
  new_information_hash text,
  root_cause text,
  owner text,
  next_action text,
  verification_method text,
  evidence text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  unique(work_key,requirement_version,problem_fingerprint)
);

alter table public.system_work_checkpoints enable row level security;
alter table public.system_work_problems enable row level security;

create policy "Authorized users read system work checkpoints" on public.system_work_checkpoints
for select to authenticated using (
  exists(select 1 from public.system_work_items item where item.work_key=system_work_checkpoints.work_key)
);
create policy "Authorized users read system work problems" on public.system_work_problems
for select to authenticated using (
  exists(select 1 from public.system_work_items item where item.work_key=system_work_problems.work_key)
);
revoke insert,update,delete on public.system_work_checkpoints from anon,authenticated;
revoke insert,update,delete on public.system_work_problems from anon,authenticated;

create or replace function public.claim_system_work_item_v2(
  target_worker text, lease_minutes integer default 15, max_attempts integer default 5
)
returns table(
  work_key text,title text,category text,risk text,detail text,progress smallint,company_id uuid,run_id uuid,
  approval_status text,approval_fingerprint text,requirement_version integer,checkpoint jsonb,context_manifest jsonb,
  evidence text,control_state text
)
language plpgsql security definer set search_path=public as $$
declare claimed record; item public.system_work_items;
begin
  select * into claimed from public.claim_system_work_item(target_worker,lease_minutes,max_attempts) limit 1;
  if claimed.work_key is null then return; end if;
  select * into item from public.system_work_items i where i.work_key=claimed.work_key;
  update public.system_work_items set execution_owner=target_worker,control_state='active' where system_work_items.work_key=claimed.work_key;
  update public.system_worker_runs set requirement_version=item.requirement_version,
    checkpoint=item.checkpoint,context_manifest_hash=md5(item.context_manifest::text)
  where id=claimed.run_id;
  return query select claimed.work_key,claimed.title,claimed.category,claimed.risk,claimed.detail,claimed.progress,
    claimed.company_id,claimed.run_id,claimed.approval_status,claimed.approval_fingerprint,item.requirement_version,
    item.checkpoint,item.context_manifest,item.evidence,'active'::text;
end $$;

create or replace function public.finish_system_work_item_v2(
  target_run uuid,target_worker text,target_status text,target_progress smallint,target_evidence text,
  target_production_status text,target_error_fingerprint text,target_outcome text,target_outcome_reason text,
  target_current_step text,target_control_state text,target_checkpoint jsonb,target_context_manifest jsonb,
  target_problem_category text default null,target_new_information_hash text default null,
  target_token_input integer default null,target_token_output integer default null
)
returns boolean language plpgsql security definer set search_path=public as $$
declare target_key text; target_version integer; prior_problem public.system_work_problems; finished boolean;
begin
  if target_control_state not in ('queued','blocked','paused','waiting_permission','token_limit','waiting_qa','worker_lost','done') then
    raise exception 'invalid_control_state';
  end if;
  select r.work_key,coalesce(r.requirement_version,i.requirement_version)
    into target_key,target_version from public.system_worker_runs r
    join public.system_work_items i on i.work_key=r.work_key
    where r.id=target_run and r.worker_id=target_worker and r.status='running' for update;
  if target_key is null then return false; end if;

  if coalesce(target_checkpoint,'{}'::jsonb) <> '{}'::jsonb then
    insert into public.system_work_checkpoints(work_key,run_id,requirement_version,milestone,checkpoint,context_manifest,evidence_refs,next_action)
    values(target_key,target_run,target_version,left(coalesce(nullif(target_current_step,''),'checkpoint'),200),target_checkpoint,
      coalesce(target_context_manifest,'{}'::jsonb),coalesce(target_checkpoint->'evidence_refs','[]'::jsonb),target_checkpoint->>'next_action');
  end if;

  if nullif(target_error_fingerprint,'') is not null then
    select * into prior_problem from public.system_work_problems p
      where p.work_key=target_key and p.requirement_version=target_version
        and p.problem_fingerprint=left(target_error_fingerprint,200) for update;
    insert into public.system_work_problems(work_key,requirement_version,problem_fingerprint,category,retry_count,retry_allowed,
      new_information_hash,owner,next_action,evidence)
    values(target_key,target_version,left(target_error_fingerprint,200),coalesce(nullif(target_problem_category,''),'unknown'),1,false,
      nullif(target_new_information_hash,''),target_worker,target_checkpoint->>'next_action',left(target_evidence,4000))
    on conflict(work_key,requirement_version,problem_fingerprint) do update set
      retry_count=public.system_work_problems.retry_count+1,
      retry_allowed=case when nullif(excluded.new_information_hash,'') is distinct from nullif(public.system_work_problems.new_information_hash,'') then true else false end,
      new_information_hash=coalesce(nullif(excluded.new_information_hash,''),public.system_work_problems.new_information_hash),
      evidence=excluded.evidence,updated_at=now();
  end if;

  select public.finish_system_work_item(target_run,target_worker,target_status,target_progress,target_evidence,
    target_production_status,target_error_fingerprint,target_outcome,target_outcome_reason) into finished;
  if not finished then return false; end if;
  update public.system_worker_runs set checkpoint=coalesce(target_checkpoint,'{}'::jsonb),
    token_input=target_token_input,token_output=target_token_output,stop_reason=target_control_state where id=target_run;
  update public.system_work_items set current_step=left(target_current_step,500),control_state=target_control_state,
    checkpoint=coalesce(target_checkpoint,'{}'::jsonb),context_manifest=coalesce(target_context_manifest,context_manifest),
    new_information_hash=nullif(target_new_information_hash,''),
    qa_owner=case when target_control_state='waiting_qa' then coalesce(qa_owner,'qa') else qa_owner end,
    updated_at=now() where system_work_items.work_key=target_key;
  return true;
end $$;

create or replace function public.recover_stale_system_work_items(stale_after_minutes integer default 10)
returns integer language plpgsql security definer set search_path=public as $$
declare stale_cutoff timestamptz; expired_runs integer:=0; lost_items integer:=0; released_claims integer:=0;
begin
  if stale_after_minutes < 2 or stale_after_minutes > 120 then raise exception 'invalid_stale_after_minutes'; end if;
  stale_cutoff:=now()-make_interval(mins=>stale_after_minutes);
  update public.system_worker_runs r set status='expired',finished_at=now(),outcome='no_output',
    outcome_reason='Worker heartbeat expired; checkpoint preserved for controlled recovery.',stop_reason='worker_lost',
    evidence=left(concat_ws(E'\n',nullif(r.evidence,''),'Worker lost: automatic retry stopped; reconcile checkpoint first.'),4000)
  where r.status='running' and (r.heartbeat_at is null or r.heartbeat_at<stale_cutoff);
  get diagnostics expired_runs=row_count;
  update public.system_work_items i set status='blocked',control_state='worker_lost',worker_id=null,heartbeat_at=null,lease_expires_at=null,
    current_step='worker_lost_reconcile_checkpoint',blocked_since=coalesce(i.blocked_since,now()),
    worker_outcome='no_output',worker_outcome_reason='Worker heartbeat expired; automatic retry stopped.',worker_outcome_at=now(),
    evidence=left(concat_ws(E'\n',nullif(i.evidence,''),'Worker lost: review the saved checkpoint and provide new information before controlled retry.'),4000),updated_at=now()
  where i.status='doing' and i.work_key<>'SYS-004'
    and (i.worker_id is null or i.heartbeat_at is null or i.heartbeat_at<stale_cutoff or i.lease_expires_at<=now())
    and not exists(select 1 from public.system_worker_runs r where r.work_key=i.work_key and r.status='running' and r.heartbeat_at>=stale_cutoff);
  get diagnostics lost_items=row_count;
  update public.system_work_items i set worker_id=null,heartbeat_at=null,lease_expires_at=null,updated_at=now()
  where i.status<>'doing' and i.worker_id is not null
    and (i.heartbeat_at is null or i.heartbeat_at<stale_cutoff or i.lease_expires_at<=now());
  get diagnostics released_claims=row_count;
  return expired_runs+lost_items+released_claims;
end $$;

create or replace function public.reset_system_work_item_retry_v2(
  target_work_key text,target_actor text,target_new_information_hash text
)
returns boolean language plpgsql security definer set search_path=public as $$
declare item public.system_work_items; problem public.system_work_problems;
begin
  if nullif(trim(target_new_information_hash),'') is null then raise exception 'new_information_required'; end if;
  select * into item from public.system_work_items i where i.work_key=target_work_key for update;
  if item.work_key is null or item.status<>'blocked' then return false; end if;
  select * into problem from public.system_work_problems p where p.work_key=item.work_key
    and p.requirement_version=item.requirement_version and p.problem_fingerprint=item.error_fingerprint for update;
  if problem.id is not null and nullif(problem.new_information_hash,'') is not distinct from trim(target_new_information_hash) then
    raise exception 'no_new_information_retry_blocked';
  end if;
  update public.system_work_problems set retry_allowed=true,new_information_hash=trim(target_new_information_hash),updated_at=now()
    where id=problem.id;
  update public.system_work_items set attempt_count=0,blocked_since=null,status='ready',control_state='queued',
    current_step='controlled_retry_after_new_information',new_information_hash=trim(target_new_information_hash),updated_at=now(),
    evidence=left(concat_ws(E'\n',nullif(evidence,''),'Controlled retry authorized by '||left(target_actor,120)||' after new information.'),4000)
    where system_work_items.work_key=item.work_key;
  return true;
end $$;

revoke all on function public.claim_system_work_item_v2(text,integer,integer) from public,anon,authenticated;
revoke all on function public.finish_system_work_item_v2(uuid,text,text,smallint,text,text,text,text,text,text,text,jsonb,jsonb,text,text,integer,integer) from public,anon,authenticated;
grant execute on function public.claim_system_work_item_v2(text,integer,integer) to service_role;
grant execute on function public.finish_system_work_item_v2(uuid,text,text,smallint,text,text,text,text,text,text,text,jsonb,jsonb,text,text,integer,integer) to service_role;
revoke all on function public.reset_system_work_item_retry_v2(text,text,text) from public,anon,authenticated;
grant execute on function public.reset_system_work_item_retry_v2(text,text,text) to service_role;

comment on function public.finish_system_work_item_v2(uuid,text,text,smallint,text,text,text,text,text,text,text,jsonb,jsonb,text,text,integer,integer) is
  'Persists a resumable checkpoint and versioned problem before ending a worker run. Repeated task+error+version without new information remains retry_allowed=false.';

notify pgrst,'reload schema';
