-- Posting Flow (Flow 3) detailed backlog.
insert into public.system_work_items(work_key,scope,title,category,status,progress,risk,detail,production_status,owner,evidence,current_step) values
('POSTING-001','platform','Posting: ห้องรออนุมัติและ Transaction Preview','report','ready',0,'critical','แสดง Intake ID ภาพ OCR คู่ค้า โครงการ รายการ ภาษี matching และ journal preview พร้อมป้ายว่ายังไม่ลงบัญชี/Stock; รองรับอนุมัติ ส่งกลับ ปฏิเสธ และพักขอข้อมูล\nตรวจรับ: ข้อมูลก่อน post ครบและสถานะไม่กำกวม','backlog_registered','Posting Flow/UX','อนุมัติขอบเขต 16/8/2569','ออกแบบ approval snapshot'),
('POSTING-002','platform','Posting: สิทธิ์ วงเงิน และลำดับอนุมัติ','tenant','ready',0,'critical','กำหนดผู้อนุมัติตามบริษัท ประเภท โครงการ ยอดเงิน และ segregation of duties; รองรับหลายชั้น ผู้แทน และหมดอายุ\nตรวจรับ: positive/negative/cross-tenant ผ่าน','backlog_registered','Posting Flow/Security','อนุมัติขอบเขต 16/8/2569','สร้าง approval policy matrix'),
('POSTING-003','platform','Posting: Final Validation และ Accounting Balance','audit','ready',0,'critical','ก่อน post ตรวจ duplicate, period, master, version, debit=credit, document/line/tax totals, PO/receipt remaining และสิทธิ์\nตรวจรับ: stale/imbalance/overbilling/closed period หยุดพร้อมข้อความไทย','backlog_registered','Posting Flow/Accounting QA','อนุมัติขอบเขต 16/8/2569','สร้าง final validation rules'),
('POSTING-004','platform','Posting: Accounting และ AP Gateway','operations','ready',0,'critical','หลังอนุมัติจึงสร้าง journal เจ้าหนี้ ภาษีซื้อ due date และ payment link ด้วย transaction/idempotency\nตรวจรับ: debit=credit, AP/tax reconcile, retry ไม่ซ้ำและ rollback ครบ','backlog_registered','Posting Flow/Accounting','อนุมัติขอบเขต 16/8/2569','กำหนด Accounting/AP command'),
('POSTING-005','platform','Posting: Stock Gateway','operations','ready',0,'critical','สร้าง receipt/issue/adjustment หลังอนุมัติ ตรวจจำนวน หน่วย คลัง โครงการ และป้องกันรับเกิน\nตรวจรับ: quantity/value reconcile, partial receipt และ double-click ถูกต้อง','backlog_registered','Posting Flow/Stock','อนุมัติขอบเขต 16/8/2569','กำหนด Stock command'),
('POSTING-006','platform','Posting: Purchase Order Gateway','operations','ready',0,'high','สร้าง PO จากใบเสนอราคาทั้งใบ/บางรายการ เก็บราคา ผู้ขาย โครงการ และ audit โดยใบเสนอราคาไม่ลงต้นทุน\nตรวจรับ: lines/qty/price ถูกต้องและเชื่อมกลับ quotation/intake','backlog_registered','Posting Flow/Purchasing','อนุมัติขอบเขต 16/8/2569','กำหนด quotation-to-PO command'),
('POSTING-007','platform','Posting: Idempotency Transaction และ Recovery','automation','ready',0,'critical','ใช้ Intake ID+Document ID+Posting Type; atomic/compensation, retry/dead-letter/heartbeat; ปิดปุ่มหลังสำเร็จและเปิดรายการเดิม\nตรวจรับ: double-click/refresh/timeout/partial failure ไม่ซ้ำหรือ orphan','backlog_registered','Posting Flow/Platform','อนุมัติขอบเขต 16/8/2569','ออกแบบ posting ledger'),
('POSTING-008','platform','Posting: Correction และ Reversal','audit','ready',0,'critical','ก่อน post แก้และตรวจใหม่; หลัง post ห้ามทับเดิม ใช้ correction/reversal พร้อมเหตุผลและ link เก่า-กลับ-ใหม่\nตรวจรับ: balances/Stock/AP ถูกต้องและ audit immutable','backlog_registered','Posting Flow/Compliance','อนุมัติขอบเขต 16/8/2569','สร้าง reversal matrix'),
('POSTING-009','platform','Posting: Audit Timeline และสถานะย้อนกลับทุก Flow','audit','ready',0,'high','ส่งสถานะและ transaction link กลับ Intake/Filter ด้วย Intake ID; เก็บ actor/time/reason/version/source/target\nตรวจรับ: trace จากภาพถึง transaction และย้อนกลับได้','backlog_registered','Posting Flow/Audit','อนุมัติขอบเขต 16/8/2569','กำหนด canonical events'),
('POSTING-010','platform','Posting: Dashboard ทุกมิติและ SLA','report','ready',0,'high','มุมมองรออนุมัติ งานฉัน พร้อมบันทึก คำเตือน ส่งกลับ ปฏิเสธ กำลังบันทึก สำเร็จ ล้มเหลว correction; filter บริษัท โครงการ คู่ค้า ประเภท งวด ยอด ผู้อนุมัติ ปลายทาง SLA\nตรวจรับ: count/amount reconcile, saved view/export ตามสิทธิ์','backlog_registered','Posting Flow/Analytics','อนุมัติขอบเขต 16/8/2569','สร้าง posting dimension view')
on conflict(work_key) do update set title=excluded.title,category=excluded.category,risk=excluded.risk,detail=excluded.detail,owner=excluded.owner,evidence=excluded.evidence,current_step=coalesce(public.system_work_items.current_step,excluded.current_step),updated_at=now();
